'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {smart} from './Format';

const clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
function nice(v){if(!Number.isFinite(v))return '—';const a=Math.abs(v);return smart(v,a<1?5:a<100?3:2)}
function timeLabel(sec,span){const d=new Date(sec*1000);return span<3*86400?d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):d.toLocaleDateString([],{month:'short',day:'numeric'});}
export default function InteractiveChart({candles=[],forecast=null,livePrice=null}){
 const canvasRef=useRef(null),hostRef=useRef(null),drag=useRef(null),[size,setSize]=useState({w:1000,h:520}),[view,setView]=useState({end:null,count:125}),[cross,setCross]=useState(null);
 const series=useMemo(()=>{const c=(candles||[]).filter(x=>[x.time,x.open,x.high,x.low,x.close].every(v=>Number.isFinite(+v))).map(x=>({...x,time:+x.time,open:+x.open,high:+x.high,low:+x.low,close:+x.close}));if(c.length&&Number.isFinite(+livePrice)){const z={...c.at(-1)},p=+livePrice;z.close=p;z.high=Math.max(z.high,p);z.low=Math.min(z.low,p);c[c.length-1]=z}return c},[candles,livePrice]);
 const points=forecast?.available?(forecast.points||[]).filter(p=>Number.isFinite(+p.price)&&Number.isFinite(+p.bar)):[];
 const maxFuture=points.length?Math.max(...points.map(p=>+p.bar)):0,totalMax=Math.max(0,series.length-1+maxFuture);
 useEffect(()=>{if(series.length)setView(v=>({count:Math.min(Math.max(70,v.count||125),Math.max(70,series.length+maxFuture)),end:totalMax}))},[series.length,maxFuture,totalMax]);
 useEffect(()=>{if(!hostRef.current)return;const ro=new ResizeObserver(es=>{const r=es[0]?.contentRect;if(r)setSize({w:Math.max(320,Math.floor(r.width)),h:Math.max(300,Math.floor(r.height))})});ro.observe(hostRef.current);return()=>ro.disconnect()},[]);
 const geom=useMemo(()=>{const w=size.w,h=size.h,pad={l:14,r:78,t:16,b:30};const plotW=w-pad.l-pad.r,plotH=h-pad.t-pad.b,end=clamp(view.end??totalMax,0,totalMax),count=clamp(view.count,30,Math.max(30,series.length+maxFuture)),start=Math.max(0,end-count+1);const visC=series.map((x,i)=>({x,i})).filter(z=>z.i>=start&&z.i<=end),visP=points.map(p=>({p,i:series.length-1+p.bar})).filter(z=>z.i>=start&&z.i<=end);const ys=[];for(const z of visC)ys.push(z.x.low,z.x.high);for(const z of visP){ys.push(z.p.price);for(const k of [50,80,90])if(z.p.ranges?.[k])ys.push(...z.p.ranges[k])}if(!ys.length)ys.push(0,1);let min=Math.min(...ys),max=Math.max(...ys),span=max-min||Math.abs(max)*.01||1;min-=span*.08;max+=span*.08;span=max-min;const X=i=>pad.l+(i-start+.5)/count*plotW,Y=v=>pad.t+(max-v)/span*plotH;return{w,h,pad,plotW,plotH,start,end,count,min,max,span,X,Y,visC,visP}},[size,view,totalMax,series,points,maxFuture]);
 const draw=useCallback(()=>{const cv=canvasRef.current;if(!cv)return;const dpr=window.devicePixelRatio||1,ctx=cv.getContext('2d'),g=geom;cv.width=Math.floor(g.w*dpr);cv.height=Math.floor(g.h*dpr);cv.style.width=`${g.w}px`;cv.style.height=`${g.h}px`;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,g.w,g.h);ctx.fillStyle='#fff';ctx.fillRect(0,0,g.w,g.h);ctx.font='10px Inter, system-ui';ctx.textBaseline='middle';
  for(let k=0;k<=5;k++){const y=g.pad.t+k*g.plotH/5,val=g.max-k*g.span/5;ctx.strokeStyle='#ecece7';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(g.pad.l,y);ctx.lineTo(g.w-g.pad.r,y);ctx.stroke();ctx.fillStyle='#777b82';ctx.fillText(nice(val),g.w-g.pad.r+8,y)}
  const spanSec=series.length>1?(series[Math.min(series.length-1,g.end)]?.time||series.at(-1).time)-(series[Math.max(0,Math.floor(g.start))]?.time||series[0].time):0;for(let k=0;k<=6;k++){const idx=Math.round(g.start+k*g.count/6);let sec;if(idx<series.length)sec=series[idx]?.time;else if(points.length){const p=points.reduce((best,x)=>Math.abs((series.length-1+x.bar)-idx)<Math.abs((series.length-1+(best?.bar||0))-idx)?x:best,points[0]);sec=p?.time}if(!sec)continue;const x=g.X(idx);ctx.fillStyle='#85888e';ctx.textAlign='center';ctx.fillText(timeLabel(sec,spanSec),x,g.h-13);ctx.textAlign='left'}
  if(g.visP.length){const upper=g.visP.filter(z=>z.p.ranges?.[80]),lower=[...upper].reverse();if(upper.length>1){ctx.beginPath();upper.forEach((z,i)=>{const x=g.X(z.i),y=g.Y(z.p.ranges[80][1]);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});lower.forEach(z=>ctx.lineTo(g.X(z.i),g.Y(z.p.ranges[80][0])));ctx.closePath();ctx.fillStyle='rgba(45,99,215,.09)';ctx.fill();}}
  const cw=clamp(g.plotW/g.count*.64,2,14);for(const z of g.visC){const c=z.x,x=g.X(z.i),up=c.close>=c.open,col=up?'#148a53':'#ce483d';ctx.strokeStyle=col;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,g.Y(c.high));ctx.lineTo(x,g.Y(c.low));ctx.stroke();ctx.fillStyle=col;const y1=g.Y(c.open),y2=g.Y(c.close);ctx.fillRect(x-cw/2,Math.min(y1,y2),cw,Math.max(1,Math.abs(y2-y1)))}
  if(g.visP.length){ctx.save();ctx.setLineDash([6,5]);ctx.lineWidth=2;ctx.strokeStyle='#2d63d7';ctx.beginPath();const lastIdx=series.length-1,last=series.at(-1);let started=false;if(last&&lastIdx>=g.start&&lastIdx<=g.end){ctx.moveTo(g.X(lastIdx),g.Y(last.close));started=true}for(const z of g.visP){if(!started){ctx.moveTo(g.X(z.i),g.Y(z.p.price));started=true}else ctx.lineTo(g.X(z.i),g.Y(z.p.price))}ctx.stroke();ctx.restore();for(const z of g.visP){ctx.fillStyle='#2d63d7';ctx.beginPath();ctx.arc(g.X(z.i),g.Y(z.p.price),3.5,0,Math.PI*2);ctx.fill()}}
  if(cross&&cross.x>=g.pad.l&&cross.x<=g.w-g.pad.r&&cross.y>=g.pad.t&&cross.y<=g.h-g.pad.b){ctx.save();ctx.setLineDash([3,4]);ctx.strokeStyle='#9ca1a8';ctx.beginPath();ctx.moveTo(cross.x,g.pad.t);ctx.lineTo(cross.x,g.h-g.pad.b);ctx.moveTo(g.pad.l,cross.y);ctx.lineTo(g.w-g.pad.r,cross.y);ctx.stroke();ctx.restore();const v=g.max-(cross.y-g.pad.t)/g.plotH*g.span;ctx.fillStyle='#111';ctx.fillRect(g.w-g.pad.r,cross.y-9,g.pad.r,18);ctx.fillStyle='#fff';ctx.font='10px ui-monospace,monospace';ctx.fillText(nice(v),g.w-g.pad.r+5,cross.y)}
 },[geom,series,points,cross]);
 useEffect(()=>{draw()},[draw]);
 const nearest=(x)=>{const g=geom,idx=clamp(Math.floor(g.start+(x-g.pad.l)/g.plotW*g.count),0,totalMax);if(idx<series.length)return{kind:'observed',idx,row:series[idx]};const z=points.reduce((b,p)=>Math.abs(series.length-1+p.bar-idx)<Math.abs(series.length-1+(b?.bar||0)-idx)?p:b,points[0]);return z?{kind:'forecast',idx:series.length-1+z.bar,row:z}:null};
 const pointerMove=e=>{const r=canvasRef.current.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(drag.current){const dx=x-drag.current.x,bars=Math.round(-dx/(geom.plotW/geom.count));if(Math.abs(bars)>=1){setView(v=>({...v,end:clamp((drag.current.end??totalMax)+bars,v.count-1,totalMax)}))}return}setCross({x,y,near:nearest(x)})};
 const wheel=e=>{e.preventDefault();const dir=e.deltaY>0?1:-1;setView(v=>{const next=clamp(Math.round(v.count*(dir>0?1.14:.86)),30,Math.max(30,series.length+maxFuture));return{...v,count:next,end:clamp(v.end??totalMax,next-1,totalMax)}})};
 const fit=()=>setView({count:Math.min(Math.max(90,series.length+maxFuture),Math.max(90,series.length+maxFuture)),end:totalMax}),latest=()=>setView(v=>({...v,end:totalMax,count:Math.min(v.count,Math.max(30,series.length+maxFuture))}));
 return <div ref={hostRef} style={{height:'100%',width:'100%',position:'relative',userSelect:'none'}}>
  <canvas ref={canvasRef} style={{display:'block',cursor:drag.current?'grabbing':'crosshair'}} onPointerDown={e=>{e.currentTarget.setPointerCapture?.(e.pointerId);const r=e.currentTarget.getBoundingClientRect();drag.current={x:e.clientX-r.left,end:view.end??totalMax}}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}} onPointerLeave={()=>{if(!drag.current)setCross(null)}} onPointerMove={pointerMove} onWheel={wheel}/>
  {cross?.near&&<div style={{position:'absolute',left:10,top:10,zIndex:4,padding:'7px 9px',border:'1px solid #e2e2dd',borderRadius:9,background:'rgba(255,255,255,.94)',fontSize:10,color:'#555',pointerEvents:'none'}}>{cross.near.kind==='observed'?<>O {nice(cross.near.row.open)} · H {nice(cross.near.row.high)} · L {nice(cross.near.row.low)} · C {nice(cross.near.row.close)}</>:<>Forecast {nice(cross.near.row.price)} · P(up) {Math.round((cross.near.row.pUp||0)*100)}%</>}</div>}
  <div style={{position:'absolute',right:10,top:10,zIndex:4,display:'flex',gap:6}}><button className="btn" onClick={fit}>Fit</button><button className="btn" onClick={latest}>Latest</button></div>
 </div>
}
