'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import InteractiveChart from './InteractiveChart';
import Score from './Score';
import SourceStatus from './SourceStatus';
import AssetSearch from './AssetSearch';
import {smart,pct,signedPct,date,shortDate,num} from './Format';

const GROUPS={
 'Crypto':[ ['BTC-USD','Bitcoin / USD','coinbase'],['ETH-USD','Ethereum / USD','coinbase'] ],
 'Stocks':[ ['AAPL','Apple','yahoo'],['RELIANCE.NS','Reliance','yahoo'],['TCS.NS','TCS','yahoo'],['NVDA','NVIDIA','yahoo'] ],
 'ETFs':[ ['SPY','S&P 500 ETF','yahoo'],['NIFTYBEES.NS','Nifty BeES','yahoo'],['QQQ','Nasdaq 100 ETF','yahoo'] ],
 'Indices':[ ['^NSEI','NIFTY 50','yahoo'],['^BSESN','BSE SENSEX','yahoo'],['^GSPC','S&P 500','yahoo'] ],
 'Futures':[ ['ES=F','E-mini S&P','yahoo'],['GC=F','Gold','yahoo'],['CL=F','Crude oil','yahoo'] ],
 'Forex':[ ['USDINR=X','USD / INR','yahoo'],['EURUSD=X','EUR / USD','yahoo'],['GBPUSD=X','GBP / USD','yahoo'],['EUR/INR','EUR / INR ECB reference','ecb'] ],
 'Funds':[ ['VFIAX','Vanguard 500 Index Fund','yahoo'],['FXAIX','Fidelity 500 Index Fund','yahoo'] }
};
const TF=['1m','5m','15m','1h','1d','1wk'],RANGES=['1d','5d','1mo','3mo','6mo','1y','2y','5y','10y','max'];
function clampInterval(i){const v=String(i||'').trim();return TF.includes(v)?v:'5m';}
function clampRange(r){const v=String(r||'').trim();return RANGES.includes(v)?v:'1mo';}
async function getJson(url){const r=await fetch(url);const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`Request ${r.status}`);return d}
function buildUrl(selection,interval,range,horizon){const q=new URLSearchParams({action:'market',provider:selection.provider,symbol:selection.symbol,interval:clampInterval(interval),range:clampRange(range),horizon:String(horizon)});return `/api/data?${q}`}

export default function MarketLab(){
 const [selection,setSelection]=useState({symbol:'BTC-USD',name:'Bitcoin / US Dollar',provider:'coinbase',assetClass:'crypto',exchange:'Coinbase'}),[saved,setSaved]=useState(false),[interval,setInterval]=useState('5m'),[range,setRange]=useState('1mo'),[horizon,setHorizon]=useState(12),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[isLoading,setIsLoading]=useState(false),[query,setQuery]=useState('BTC-USD'),[options,setOptions]=useState(null),[optionsLoading,setOptionsLoading]=useState(false),[streamPrice,setStreamPrice]=useState(null),[streamTime,setStreamTime]=useState(null),timer=useRef(null);
 const isDailyOnly=selection.provider==='amfi'||selection.provider==='ecb'||selection.assetClass==='mutual_fund';
 useEffect(()=>{try{const q=new URLSearchParams(window.location.search),symbol=q.get('symbol'),provider=q.get('provider'),name=q.get('name'),assetClass=q.get('assetClass');if(symbol&&provider){const x={symbol,provider,name:name||symbol,assetClass:assetClass||'market',exchange:''};setSelection(x);setQuery(symbol)}}catch{}},[]);
 useEffect(()=>{try{const a=JSON.parse(localStorage.getItem('zachitan.watchlist.v4')||'[]');setSaved(a.some(x=>x.symbol===selection.symbol&&x.provider===selection.provider))}catch{setSaved(false)}},[selection]);
const load=async(s=selection,i=interval,r=range,h=horizon,quiet=false)=>{if(isLoading)return;setIsLoading(true);if(!quiet)setLoading(true);setError('');try{const d=await getJson(buildUrl(s,i,r,h));setData(d)}catch(e){setError(e.message)}finally{setIsLoading(false);if(!quiet)setLoading(false)}};
  useEffect(()=>{let mounted=true;(async()=>{try{await load(selection,interval,range,horizon)}catch{}}finally{mounted=false}})();globalThis.clearInterval(timer.current);const poll=()=>{if(!document.hidden&&mounted)load(selection,interval,range,horizon,true)};timer.current=globalThis.setInterval(poll,selection.provider==='coinbase'?15000:45000);return()=>{globalThis.clearInterval(timer.current)}};

 useEffect(()=>{setStreamPrice(null);setStreamTime(null);if(selection.provider!=='coinbase')return;let ws;try{ws=new WebSocket('wss://ws-feed.exchange.coinbase.com');ws.onopen=()=>ws.send(JSON.stringify({type:'subscribe',product_ids:[selection.symbol],channels:['ticker']}));ws.onmessage=e=>{try{const x=JSON.parse(e.data);if(x.type==='ticker'&&x.product_id===selection.symbol&&Number.isFinite(+x.price)){setStreamPrice(+x.price);setStreamTime(x.time||new Date().toISOString())}}catch{}}}catch{}return()=>{try{ws?.close()}catch{}}},[selection.provider,selection.symbol]);
 const choose=x=>{const s={symbol:x.symbol,name:x.name||x.symbol,provider:x.provider||'yahoo',assetClass:x.assetClass||'market',exchange:x.exchange||''};setSelection(s);setQuery(s.symbol);setOptions(null);if(s.provider==='amfi'||s.provider==='ecb'||s.assetClass==='mutual_fund'){setInterval('1d');if(['1d','5d'].includes(range))setRange('2y')}};
 const loadOptions=async()=>{setOptionsLoading(true);try{const d=await getJson(`/api/data?action=options&symbol=${encodeURIComponent(selection.symbol)}`);setOptions(d)}catch(e){setOptions({state:'DEGRADED',message:e.message,calls:[],puts:[]})}finally{setOptionsLoading(false)}};
 const f=data?.forecast,v=data?.validation,ind=data?.indicators,m=data?.microstructure,quote=data?.quote||{},meta=data?.meta||{},displayPrice=streamPrice??quote.price??data?.candles?.at(-1)?.close;
 const change=Number.isFinite(+displayPrice)&&Number.isFinite(+quote.previousClose)&&+quote.previousClose?+displayPrice/+quote.previousClose-1:null;
 const toggleWatch=()=>{try{let a=JSON.parse(localStorage.getItem('zachitan.watchlist.v4')||'[]');const k=x=>x.symbol===selection.symbol&&x.provider===selection.provider;if(a.some(k)){a=a.filter(x=>!k(x));setSaved(false)}else{a.unshift({...selection,name:meta.name||selection.name});a=a.slice(0,40);setSaved(true)}localStorage.setItem('zachitan.watchlist.v4',JSON.stringify(a));window.dispatchEvent(new Event('zachitan-watchlist'))}catch{}};
 const exportCsv=()=>{const rows=data?.candles||[];if(!rows.length)return;const csv=['time,open,high,low,close,volume',...rows.map(x=>[new Date(x.time*1000).toISOString(),x.open,x.high,x.low,x.close,x.volume||0].join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`zachitan-${selection.symbol.replace(/[^A-Za-z0-9.-]/g,'_')}-${interval}.csv`;a.click();URL.revokeObjectURL(a.href)};
 const canOptions=['stock','etf','index'].includes(selection.assetClass)||['EQUITY','ETF','INDEX'].includes(meta.assetClass);
 const forecastPoints=f?.available?f.points||[]:[];
 const optionsNear=useMemo(()=>{if(!options?.calls?.length&&!options?.puts?.length)return[];const spot=options.metrics?.spot||+quote.price||0;return[...(options.calls||[]).map(x=>({...x,type:'Call'})),...(options.puts||[]).map(x=>({...x,type:'Put'}))].sort((a,b)=>Math.abs(a.strike-spot)-Math.abs(b.strike-spot)).slice(0,20)},[options,quote.price]);
 return <div className={`marketLayout ${loading?'loading':''}`}>
  <aside className="card controls">
   <label className="label">Search any supported instrument</label>
   <AssetSearch value={query} onChange={setQuery} onSelect={choose} placeholder="Apple, NIFTY 50, USDINR, gold, Bitcoin, fund…" label="Search supported instruments" help="Focus for suggestions"/>
   <div className="controlGroup"><label className="label">Quick markets</label>{Object.entries(GROUPS).map(([g,rows])=><div key={g} style={{marginBottom:9}}><div style={{fontSize:10,color:'#85888e',margin:'0 0 5px'}}>{g}</div><div className="chips">{rows.map(([s,n,p])=><button key={s} className={`chip ${selection.symbol===s?'on':''}`} title={n} onClick={()=>choose({symbol:s,name:n,provider:p,assetClass:g.toLowerCase().replace('funds','mutual_fund').replace('stocks','stock').replace('indices','index').replace('futures','future').replace('forex','forex').replace('etfs','etf').replace('crypto','crypto')})}>{s}</button>)}</div></div>)}</div>
   <div className="controlGroup"><label className="label">Candle / observation size</label><div className="chips">{TF.map(t=><button key={t} disabled={isDailyOnly&&t!=='1d'} className={`chip ${interval===t?'on':''}`} onClick={()=>setInterval(t)}>{t}</button>)}</div>{isDailyOnly&&<p className="muted" style={{fontSize:10,lineHeight:1.4}}>Funds and official reference rates are end-of-day observations; Zachitan does not fabricate intraday candles.</p>}</div>
   <div className="controlGroup"><label className="label">Visible history</label><div className="chips">{RANGES.map(r=><button key={r} className={`chip ${range===r?'on':''}`} onClick={()=>setRange(r)}>{r}</button>)}</div></div>
   <div className="controlGroup"><label className="label">Forecast horizon</label><select className="select" value={horizon} onChange={e=>setHorizon(+e.target.value)}>{[3,5,8,12,20,30,50].map(x=><option key={x} value={x}>{x} observations ahead</option>)}</select></div>
   <div className="controlGroup"><button className="btn primary" style={{width:'100%'}} onClick={()=>load()}>Refresh source data</button></div>
   <div className="controlGroup notice">Timing depends on the source and venue. A value can be live, delayed, end-of-day or a reference rate. Zachitan displays that state instead of relabeling everything “live.”</div>
  </aside>
  <div className="marketMain">
   {error&&<div className="error"><b>Market source failed.</b> {error}. No substitute price was generated.</div>}
   <div className="card pad">
    <div className="assetHead"><div><p className="eyebrow">{meta.assetClass||selection.assetClass} · {meta.exchange||selection.exchange||selection.provider}</p><h2>{meta.name||selection.name||selection.symbol}</h2><div className="assetSub">{selection.symbol} · {meta.currency||''} · {meta.marketState||data?.quality?.timing||'source timing'} · {data?.quality?.rows||0} clean observations</div><button className="btn" style={{marginTop:9}} onClick={toggleWatch}>{saved?'★ In watchlist':'☆ Add to watchlist'}</button></div><div className="quote"><div className="quotePrice">{smart(displayPrice)}</div><div className={`quoteSub ${change>0?'positive':change<0?'negative':''}`}>{change==null?'Previous-close comparison unavailable':`${signedPct(change)} vs previous close`} · {date(streamTime||quote.time||data?.quality?.newest)}</div></div></div>
    <div className="grid5" style={{marginTop:18}}><div className="metric"><span>RSI 14</span><b>{num(ind?.rsi14,1)}</b><small>Momentum context</small></div><div className="metric"><span>ATR / price</span><b>{pct(ind?.atrPct,2)}</b><small>Recent range scale</small></div><div className="metric"><span>20-observation return vol</span><b>{pct(ind?.realizedVol20,2)}</b><small>Log-return dispersion</small></div><div className="metric"><span>52-window position</span><b>{pct(ind?.position52,0)}</b><small>Within available ~252 observations</small></div><div className="metric"><span>Data freshness</span><b>{data?.quality?.freshnessScore??'—'}</b><small>0–100 source timing score</small></div></div>
   </div>
   <div className="card chartPanel"><div className="chartToolbar"><div><b style={{fontSize:13}}>Interactive observed + forecast chart</b><div className="muted" style={{fontSize:10,marginTop:2}}>Drag to pan · wheel/pinch to zoom · use Fit/Latest to reset</div></div><SourceStatus provider={data?.provenance?.provider||selection.provider} state="CONNECTED" /></div><div className="chartWrap"><InteractiveChart candles={data?.candles||[]} forecast={f} livePrice={displayPrice}/></div><div className="chartLegend"><span>Observed candlesticks use source OHLC. Blue dashed median + dotted 80% bounds are experimental forecast checkpoints.</span><span>{data?.provenance?.provider||'Source pending'} · synthetic: false</span></div></div>
   <div className="forecastPanel">
    <div className="card forecastHero"><p className="eyebrow">Experimental Zachitan forecast</p>{f?.available?<><div className="forecastCenter">{smart(f.center)}</div><div className="muted" style={{fontSize:12}}>{horizon} observations ahead · current {smart(f.current)} · implied center change {signedPct(f.center/f.current-1)}</div><div className="rangeList">{[50,80,90,95,99].map(k=><div className="rangeRow" key={k}><span>{k}%</span><b>{f.ranges?.[k]?`${smart(f.ranges[k][0])} — ${smart(f.ranges[k][1])}`:'Withheld'}</b><small>{f.ranges?.[k]?'empirical interval':'needs more effective evidence'}</small></div>)}</div></>:<div className="notice">{f?.reason||'Forecast not available for the current history.'}</div>}</div>
    <div className="card pad"><Score value={f?.evidenceScore||0}/><div className="divider"/><Score value={f?.calibrationScore||0} title="Calibration score" copy="How coherent the historical walk-forward errors and interval coverage are. It is not probability of being correct."/><div className="divider"/><div className="grid2"><div className="metric"><span>Chance above current</span><b>{pct(f?.direction?.up)}</b></div><div className="metric"><span>Chance below current</span><b>{pct(f?.direction?.down)}</b></div><div className="metric"><span>Effective examples</span><b>{num(f?.effectiveN,1)}</b></div><div className="metric"><span>Walk-forward checks</span><b>{v?.checks??0}</b></div></div></div>
   </div>
   <div className="card pad"><div className="sectionHead" style={{marginBottom:8}}><div><p className="eyebrow">Next five checkpoints</p><h2 style={{fontSize:25}}>Not one frozen target</h2></div><p>Each checkpoint is built from the same evidence set at a different point inside the selected horizon. These are conditional distributions, not promised future prints.</p></div>{forecastPoints.length?<div style={{overflow:'auto'}}><table className="pointTable"><thead><tr><th>Forecast time</th><th>Point</th><th>Change</th><th>P(up)</th><th>50% interval</th><th>80% interval</th><th>90% interval</th></tr></thead><tbody>{forecastPoints.map((p,i)=><tr key={`${p.time}:${i}`}><td>{date(p.time)}</td><td><b>{smart(p.price)}</b></td><td className={p.change>=0?'positive':'negative'}>{signedPct(p.change)}</td><td>{pct(p.pUp)}</td><td>{p.ranges?.[50]?`${smart(p.ranges[50][0])}–${smart(p.ranges[50][1])}`:'—'}</td><td>{p.ranges?.[80]?`${smart(p.ranges[80][0])}–${smart(p.ranges[80][1])}`:'—'}</td><td>{p.ranges?.[90]?`${smart(p.ranges[90][0])}–${smart(p.ranges[90][1])}`:'—'}</td></tr>)}</tbody></table></div>:<div className="notice">No checkpoint path is shown when there is not enough clean historical evidence.</div>}</div>
   <div className="grid2">
    <div className="card pad"><p className="eyebrow">Evidence + validation</p><h3 style={{fontSize:23,margin:'0 0 12px'}}>What backs the forecast</h3><div className="kv"><div className="kvRow"><span>Chronological direction accuracy</span><b>{pct(v?.directionAccuracy)}</b></div><div className="kvRow"><span>Median historical price error</span><b>{pct(v?.medianAbsPctError)}</b></div><div className="kvRow"><span>High-confidence selective accuracy</span><b>{pct(v?.selectiveAccuracy)}</b></div><div className="kvRow"><span>80% interval historical coverage</span><b>{pct(v?.coverage?.[80])}</b></div><div className="kvRow"><span>Recent support</span><b>{smart(f?.breakout?.support)}</b></div><div className="kvRow"><span>Recent resistance</span><b>{smart(f?.breakout?.resistance)}</b></div><div className="kvRow"><span>P(touch/break above)</span><b>{pct(f?.breakout?.up)}</b></div><div className="kvRow"><span>P(touch/break below)</span><b>{pct(f?.breakout?.down)}</b></div></div><p className="bodycopy" style={{fontSize:11}}>Validation is walk-forward: historical checkpoints are evaluated only against observations that came later. Zachitan does not disclose the production feature transformations, weighting scheme, or internal implementation on this page.</p></div>
    <div className="card pad"><p className="eyebrow">Market mechanics</p><h3 style={{fontSize:23,margin:'0 0 12px'}}>{m?'Native microstructure':'Source-available technical context'}</h3>{m?<div className="kv"><div className="kvRow"><span>Best bid / ask</span><b>{smart(m.bestBid)} / {smart(m.bestAsk)}</b></div><div className="kvRow"><span>Spread</span><b>{num(m.spreadBps,2)} bps</b></div><div className="kvRow"><span>Visible book imbalance</span><b>{signedPct(m.bookImbalance)}</b></div><div className="kvRow"><span>Recent aggressive trade imbalance</span><b>{signedPct(m.tradeImbalance)}</b></div></div>:<div className="kv"><div className="kvRow"><span>Distance from 20 average</span><b>{signedPct(ind?.distanceSma20)}</b></div><div className="kvRow"><span>Distance from 50 average</span><b>{signedPct(ind?.distanceSma50)}</b></div><div className="kvRow"><span>Volume surprise</span><b>{num(ind?.volumeZ,2)} z</b></div><div className="kvRow"><span>1-observation return</span><b>{signedPct(ind?.return1)}</b></div><div className="kvRow"><span>5-observation return</span><b>{signedPct(ind?.return5)}</b></div></div>}<p className="bodycopy" style={{fontSize:11}}>Order-book and trade-flow fields appear only where the connected venue provides them. Zachitan does not infer a fake order book for instruments that do not expose one.</p></div>
   </div>
   {canOptions&&<div className="card pad"><div className="sectionHead"><div><p className="eyebrow">Options lens</p><h2 style={{fontSize:25}}>Chain and positioning</h2></div><p>The public beta requests a real published option chain when available. It never substitutes invented contracts if the upstream session is unavailable.</p></div><button className="btn primary" onClick={loadOptions} disabled={optionsLoading}>{optionsLoading?'Loading option chain…':'Load option chain'}</button>{options&&<div style={{marginTop:14}}><div className={options.state==='CONNECTED'?'success':'notice'}>{options.state==='CONNECTED'?`Chain connected. Expiration ${options.expiration?shortDate(options.expiration):'source default'}.`:(options.message||'Option chain degraded.')}</div>{options.state==='CONNECTED'&&<><div className="grid3" style={{marginTop:12}}><div className="metric"><span>Put / call volume</span><b>{num(options.metrics?.putCallVolume,2)}</b></div><div className="metric"><span>Put / call open interest</span><b>{num(options.metrics?.putCallOpenInterest,2)}</b></div><div className="metric"><span>Nearest ATM implied vol</span><b>{pct(options.metrics?.nearestAtmIv,1)}</b></div></div><div style={{overflow:'auto',marginTop:12}}><table className="table"><thead><tr><th>Contract</th><th>Type</th><th>Strike</th><th>Bid</th><th>Ask</th><th>Last</th><th>Volume</th><th>OI</th><th>IV</th></tr></thead><tbody>{optionsNear.map(x=><tr key={x.contractSymbol}><td>{x.contractSymbol}</td><td>{x.type}</td><td>{smart(x.strike)}</td><td>{smart(x.bid)}</td><td>{smart(x.ask)}</td><td>{smart(x.lastPrice)}</td><td>{num(x.volume,0)}</td><td>{num(x.openInterest,0)}</td><td>{pct(x.impliedVolatility)}</td></tr>)}</tbody></table></div></>}</div>}</div>}
   <div className="card pad"><div className="sectionHead" style={{marginBottom:8}}><div><p className="eyebrow">Raw evidence audit</p><h2 style={{fontSize:25}}>Inspect the observations under the model</h2></div><button className="btn" onClick={exportCsv}>Export CSV</button></div><div style={{overflow:'auto',maxHeight:330}}><table className="table"><thead><tr><th>Time</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th></tr></thead><tbody>{(data?.candles||[]).slice(-40).reverse().map((x,i)=><tr key={`${x.time}:${i}`}><td>{date(x.time)}</td><td>{smart(x.open)}</td><td>{smart(x.high)}</td><td>{smart(x.low)}</td><td><b>{smart(x.close)}</b></td><td>{num(x.volume,3)}</td></tr>)}</tbody></table></div></div>
   <div className="card pad"><p className="eyebrow">Source contract</p><div className="grid4"><div className="metric"><span>Provider</span><b style={{fontSize:15}}>{data?.provenance?.provider||'—'}</b></div><div className="metric"><span>Timing</span><b style={{fontSize:15}}>{data?.provenance?.cadence||data?.quality?.timing||'—'}</b></div><div className="metric"><span>Newest observation</span><b style={{fontSize:15}}>{shortDate(data?.quality?.newest)}</b></div><div className="metric"><span>Synthetic live values</span><b style={{fontSize:15}}>{data?.provenance?.synthetic===false?'No':'Unknown'}</b></div></div><p className="bodycopy" style={{fontSize:11}}>{data?.provenance?.rights||''}</p></div>
  </div>
 </div>
}
