'use client';
import {useEffect,useMemo,useState} from 'react';
import SourceStatus from './SourceStatus';
import AssetSearch from './AssetSearch';

const TOPICS=['global markets','India markets','NIFTY 50','US stocks','Federal Reserve','RBI rates','inflation','earnings','crude oil','gold','AI semiconductors','cryptocurrency','geopolitics markets'];
async function fetchJson(url){const r=await fetch(url),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`Request ${r.status}`);return d}
export default function NewsResearch(){
 const [q,setQ]=useState('global markets'),[news,setNews]=useState(null),[filingQ,setFilingQ]=useState('AAPL'),[filings,setFilings]=useState(null),[error,setError]=useState(''),[newsLoading,setNewsLoading]=useState(false),[filingsLoading,setFilingsLoading]=useState(false);
 const topicSuggestions=useMemo(()=>{const t=q.trim().toLowerCase();return TOPICS.filter(x=>!t||x.toLowerCase().includes(t)).slice(0,6)},[q]);
 const loadNews=async(next=q)=>{setNewsLoading(true);setError('');try{setNews(await fetchJson(`/api/data?action=news&q=${encodeURIComponent(next)}`))}catch(e){setError(e.message)}finally{setNewsLoading(false)}};
 const loadFilings=async(next=filingQ)=>{setFilingsLoading(true);setError('');try{setFilings(await fetchJson(`/api/data?action=filings&q=${encodeURIComponent(next)}`))}catch(e){setError(e.message)}finally{setFilingsLoading(false)}};
 useEffect(()=>{loadNews();loadFilings()},[]);
 const chooseCompany=x=>{setFilingQ(x.symbol);loadFilings(x.symbol)};
 return <div>
  {error&&<div className="error">{error}</div>}
  <div className="grid2">
   <section className={`card pad ${newsLoading?'loading':''}`}><p className="eyebrow">Fresh reporting</p><h3 className="panelTitle">Search the current news evidence</h3><div className="searchAction"><div className="searchWrap"><input className="input" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&loadNews()} placeholder="Company, market, event or topic…" autoComplete="off"/><div className="topicSuggest">{topicSuggestions.map(x=><button type="button" key={x} onClick={()=>{setQ(x);loadNews(x)}}>{x}</button>)}</div></div><button className="btn primary" onClick={()=>loadNews()}>{newsLoading?'Searching…':'Search'}</button></div>{news&&<div style={{marginTop:14}}><SourceStatus provider={news.provider} state={news.state}/><p className="bodycopy compactCopy">Headlines and publisher metadata are research evidence. A headline is not automatically treated as verified fact or predictive signal.</p></div>}</section>
   <section className={`card pad ${filingsLoading?'loading':''}`}><p className="eyebrow">Official company disclosures</p><h3 className="panelTitle">Find a company, then check filings</h3><AssetSearch value={filingQ} onChange={setFilingQ} onSelect={chooseCompany} placeholder="Apple, Microsoft, NVIDIA, AAPL…" filter={x=>['stock','etf'].includes(x.assetClass)} label="Search company for filings" help="Focus for company suggestions"/><div style={{marginTop:14}} className="filingStatus">{filings&&<SourceStatus provider="U.S. SEC EDGAR" state={filings.state}/>}<button className="btn" onClick={()=>loadFilings()}>{filingsLoading?'Checking…':'Check ticker'}</button></div>{filings?.state==='GATED'&&<div className="infoPanel" style={{marginTop:10}}><b>Official SEC search is available.</b><p>The automated extraction connector is intentionally off until this deployment has a real operator identity. That is a compliance gate, not missing market data.</p>{filings.officialSearch&&<a className="textLink" href={filings.officialSearch} target="_blank" rel="noreferrer">Open SEC company search ↗</a>}</div>}{filings?.company&&<p className="bodycopy"><b>{filings.company.ticker}</b> · {filings.company.name} · CIK {filings.company.cik}</p>}</section>
  </div>
  <section className="section"><div className="sectionHead"><div><p className="eyebrow">News results</p><h2>Publisher-attributed evidence</h2></div><p>Scan the reporting layer, then open important stories and trace material claims to the publisher or a primary source.</p></div><div className="articleGrid">{news?.articles?.length?news.articles.map((a,i)=><a key={`${a.url}:${i}`} className="card article" href={a.url} target="_blank" rel="noreferrer"><div className="articleDomain">{a.domain||a.provider||'publisher'}</div><h3>{a.title}</h3><p>{a.seenDate||'Current index'}</p></a>):<div className="emptyState card pad"><div className="emptyGlyph">▤</div><h3>No current articles returned</h3><p>Try a broader company, sector, market or event query.</p></div>}</div></section>
  <section className="section"><div className="sectionHead"><div><p className="eyebrow">Filings</p><h2>Primary company disclosures</h2></div><p>Automated rows appear only when the SEC connector is configured correctly. Until then, Zachitan links to the official search instead of inventing or scraping around the gate.</p></div><div className="card pad">{filings?.filings?.length?<div style={{overflow:'auto'}}><table className="table"><thead><tr><th>Form</th><th>Filed</th><th>Report</th><th>Description</th><th>Source</th></tr></thead><tbody>{filings.filings.map((x,i)=><tr key={`${x.accession}:${i}`}><td>{x.form}</td><td>{x.filingDate}</td><td>{x.reportDate}</td><td style={{textAlign:'left'}}>{x.description}</td><td>{x.url?<a href={x.url} target="_blank" rel="noreferrer">SEC</a>:'—'}</td></tr>)}</tbody></table></div>:<div className="filingsEmpty"><div><b>{filings?.state==='GATED'?'Automated SEC rows are disabled in this beta.':'No filing rows returned for this query.'}</b><p>{filings?.state==='GATED'?'Use the official SEC search above. Zachitan keeps this state explicit so a connectivity/compliance limitation is not mistaken for “no filings”.':'Try another ticker or company suggestion above.'}</p></div></div>}</div></section>
  <section className="section"><div className="grid3"><div className="card pad"><p className="eyebrow">Evidence order</p><h3>Price move → filing → reporting.</h3><p className="bodycopy">For company-specific moves, primary disclosures and exchange announcements should outrank secondary commentary when available.</p></div><div className="card pad"><p className="eyebrow">Time discipline</p><h3>Article time is not event time.</h3><p className="bodycopy">A newly indexed article can describe an older event, so Zachitan preserves publisher timing rather than manufacturing a new causal timestamp.</p></div><div className="card pad"><p className="eyebrow">Context discipline</p><h3>Sentiment is context, not truth.</h3><p className="bodycopy">The research layer does not turn every positive or negative headline into an investment instruction.</p></div></div></section>
 </div>
}
