'use client';
import {useEffect,useMemo,useState} from 'react';
import {smart,pct,shortDate} from './Format';
import MiniLine from './MiniLine';
import AssetSearch from './AssetSearch';

function xnpv(rate,cash){if(rate<=-0.999)return Infinity;const t0=cash[0]?.date||0;return cash.reduce((s,x)=>s+x.value/Math.pow(1+rate,(x.date-t0)/(365.25*86400000)),0)}
function xirr(cash){if(cash.length<2)return null;let lo=-.99,hi=10,flo=xnpv(lo,cash),fhi=xnpv(hi,cash);if(!Number.isFinite(flo)||!Number.isFinite(fhi)||flo*fhi>0)return null;for(let i=0;i<100;i++){const m=(lo+hi)/2,f=xnpv(m,cash);if(Math.abs(f)<1e-7)return m;if(flo*f<=0){hi=m;fhi=f}else{lo=m;flo=f}}return(lo+hi)/2}
function simulate(candles,amount){const rows=(candles||[]).filter(x=>x.close>0).sort((a,b)=>a.time-b.time);if(rows.length<60||!(amount>0))return null;const buys=[],seen=new Set();let units=0,invested=0;for(const c of rows){const d=new Date(c.time*1000),key=`${d.getUTCFullYear()}-${d.getUTCMonth()}`;if(seen.has(key))continue;seen.add(key);const u=amount/c.close;units+=u;invested+=amount;buys.push({time:c.time,price:c.close,units:u,totalUnits:units,invested})}if(!buys.length)return null;const last=rows.at(-1),value=units*last.close,cash=buys.map(b=>({date:b.time*1000,value:-amount}));cash.push({date:last.time*1000,value});const irr=xirr(cash);let peak=0,maxDd=0;const timeline=[];for(const c of rows){const active=buys.filter(b=>b.time<=c.time);if(!active.length)continue;const u=active.at(-1).totalUnits,val=u*c.close;peak=Math.max(peak,val);if(peak>0)maxDd=Math.min(maxDd,val/peak-1);timeline.push({time:c.time,value:val})}return{invested,value,gain:value/invested-1,irr,maxDrawdown:maxDd,units,purchases:buys.length,lastPrice:last.close,start:buys[0].time,end:last.time,buys,timeline}}
export default function SipLab(){
 const [amount,setAmount]=useState(10000),[selection,setSelection]=useState({symbol:'VFIAX',name:'Vanguard 500 Index Fund Admiral',provider:'yahoo',assetClass:'mutual_fund'}),[query,setQuery]=useState('Vanguard 500'),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let live=true;(async()=>{setError('');setLoading(true);try{const q=new URLSearchParams({action:'market',provider:selection.provider,symbol:selection.symbol,interval:'1d',range:'5y',horizon:'12'}),r=await fetch(`/api/data?${q}`),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Fund source failed');if(live)setData(d)}catch(e){if(live)setError(e.message)}finally{if(live)setLoading(false)}})();return()=>{live=false}},[selection]);
 const s=useMemo(()=>simulate(data?.candles,+amount||0),[data,amount]);
 const choose=x=>{setSelection(x);setQuery(x.name||x.symbol)};
 return <section className="section"><div className="sectionHead"><div><p className="eyebrow">SIP / recurring-investment lab</p><h2>Replay a real contribution schedule</h2></div><p>Monthly purchases use the first available observation in each month. No invented NAV, dividend, tax, fee or missing observation is inserted.</p></div><div className="grid2">
  <div className="card pad"><label className="label">Search mutual fund / AMFI scheme</label><AssetSearch value={query} onChange={setQuery} onSelect={choose} placeholder="Vanguard 500, Parag Parikh, Axis, scheme code…" filter={x=>x.assetClass==='mutual_fund'||x.provider==='amfi'} label="Search mutual funds" help="Focus for fund suggestions"/><div className="selectedInstrument"><span>Selected</span><b>{selection.name||selection.symbol}</b><small>{selection.symbol} · {selection.provider==='amfi'?'AMFI NAV series':selection.provider}</small></div><div className="controlGroup"><label className="label">Contribution per month</label><div className="moneyInput"><span>{data?.meta?.currency||'Amount'} / month</span><input className="input" type="number" min="1" step="500" value={amount} onChange={e=>setAmount(e.target.value)}/></div></div><div className="notice" style={{marginTop:13}}>This is a historical contribution simulation, not a promised future return. The currency label follows the selected source; the amount is a unit contribution when the fund is not INR-denominated.</div>{error&&<div className="error" style={{marginTop:10}}>{error}</div>}</div>
  <div className={`card pad ${loading?'loading':''}`}><p className="eyebrow">Historical simulation</p><h3 className="panelTitle">{data?.meta?.name||selection.name}</h3>{s?<><div className="grid3"><div className="metric"><span>Total contributed</span><b>{smart(s.invested)}</b></div><div className="metric"><span>Ending value</span><b>{smart(s.value)}</b></div><div className="metric"><span>Gain / loss</span><b className={s.gain>=0?'positive':'negative'}>{pct(s.gain)}</b></div><div className="metric"><span>XIRR</span><b>{pct(s.irr)}</b></div><div className="metric"><span>Plan drawdown</span><b>{pct(s.maxDrawdown)}</b></div><div className="metric"><span>Purchases</span><b>{s.purchases}</b></div></div><MiniLine values={s.timeline.map(x=>x.value)} label="Historical simulated plan value · contribution timing follows actual available observations"/><p className="bodycopy" style={{fontSize:11}}>History: {shortDate(s.start)} to {shortDate(s.end)} · ending observation {smart(s.lastPrice)} · source {data?.provenance?.provider}. Past simulated performance is not a forecast.</p></>:<div className="notice">{loading?'Loading verified history…':'Waiting for enough clean daily history.'}</div>}</div>
 </div></section>
}
