'use client';
import {useEffect,useMemo,useState} from 'react';
import {smart,pct,shortDate} from './Format';
import MiniLine from './MiniLine';
import AssetSearch from './AssetSearch';
import {simulateRecurring} from '@/lib/sip.mjs';

export default function SipLab(){
 const [amount,setAmount]=useState(10000),[selection,setSelection]=useState({symbol:'VFIAX',name:'Vanguard 500 Index Fund Admiral',provider:'yahoo',assetClass:'mutual_fund'}),[query,setQuery]=useState('Vanguard 500'),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let live=true;const ctrl=new AbortController();(async()=>{setError('');setLoading(true);try{const q=new URLSearchParams({action:'market',provider:selection.provider,symbol:selection.symbol,interval:'1d',range:'5y',horizon:'12'}),r=await fetch(`/api/data?${q}`,{signal:ctrl.signal}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Fund source failed');if(live)setData(d)}catch(e){if(live&&e?.name!=='AbortError')setError(e.message)}finally{if(live)setLoading(false)}})();return()=>{live=false;ctrl.abort()}},[selection]);
 const s=useMemo(()=>simulateRecurring(data?.candles,+amount||0),[data,amount]);
 const choose=x=>{setSelection(x);setQuery(x.name||x.symbol)};
 return <section className="section"><div className="sectionHead"><div><p className="eyebrow">SIP / recurring-investment lab</p><h2>Replay a real contribution schedule</h2></div><p>Monthly purchases use the first available observation in each month. Cash flows are included in XIRR; drawdown is measured on the underlying NAV/price so contributions cannot artificially hide losses.</p></div><div className="grid2">
  <div className="card pad"><label className="label">Search mutual fund / AMFI scheme</label><AssetSearch value={query} onChange={setQuery} onSelect={choose} placeholder="Vanguard 500, Parag Parikh, Axis, scheme code…" filter={x=>x.assetClass==='mutual_fund'||x.provider==='amfi'} label="Search mutual funds" help="Focus for fund suggestions"/><div className="selectedInstrument"><span>Selected</span><b>{selection.name||selection.symbol}</b><small>{selection.symbol} · {selection.provider==='amfi'?'AMFI NAV series':selection.provider}</small></div><div className="controlGroup"><label className="label">Contribution per month</label><div className="moneyInput"><span>{data?.meta?.currency||'Amount'} / month</span><input className="input" type="number" min="1" step="500" value={amount} onChange={e=>setAmount(e.target.value)}/></div></div><div className="notice" style={{marginTop:13}}>Historical replay only. Taxes, fees and missing distributions are not invented. Currency follows the selected source.</div>{error&&<div className="error" style={{marginTop:10}}>{error}</div>}</div>
  <div className={`card pad ${loading?'loading':''}`}><p className="eyebrow">Historical simulation</p><h3 className="panelTitle">{data?.meta?.name||selection.name}</h3>{s?<><div className="grid3"><div className="metric"><span>Total contributed</span><b>{smart(s.invested)}</b></div><div className="metric"><span>Ending value</span><b>{smart(s.value)}</b></div><div className="metric"><span>Gain / loss</span><b className={s.gain>=0?'positive':'negative'}>{pct(s.gain)}</b></div><div className="metric"><span>XIRR</span><b>{pct(s.irr)}</b></div><div className="metric"><span>Underlying max drawdown</span><b>{pct(s.underlyingMaxDrawdown)}</b></div><div className="metric"><span>Purchases</span><b>{s.purchases}</b></div></div><MiniLine values={s.timeline.map(x=>x.value)} label="Historical simulated plan value · contribution timing follows actual observations"/><p className="bodycopy" style={{fontSize:11}}>History: {shortDate(s.start)} to {shortDate(s.end)} · ending observation {smart(s.lastPrice)} · source {data?.provenance?.provider}. Past simulated performance is not a forecast.</p></>:<div className="notice">{loading?'Loading verified history…':'Waiting for enough clean daily history.'}</div>}</div>
 </div></section>
}
