'use client';
import {useEffect,useState} from 'react';
import SourceStatus from './SourceStatus';
import {num,date} from './Format';
import MiniLine from './MiniLine';

const EXPECTED=[['weather','Open-Meteo'],['earthquakes','USGS'],['naturalEvents','NASA EONET'],['macro','World Bank'],['rates','U.S. Treasury'],['cyber','NIST NVD'],['knownExploited','CISA KEV'],['spaceWeather','NOAA SWPC']];
function KV({l,v}){return <div className="kvRow"><span>{l}</span><b>{v??'—'}</b></div>}
function Events({rows=[],render}){return <div className="eventList">{rows.length?rows.slice(0,10).map((x,i)=><div className="event" key={x.id||x.cveID||i}>{render(x)}</div>):<p className="muted" style={{fontSize:11}}>No current rows in this feed.</p>}</div>}
function LoadingRows({n=4}){return <div className="skeletonStack">{Array.from({length:n},(_,i)=><div className="skeletonLine" key={i}/>)}</div>}
function FeedError({source}){return <div className="feedDegraded"><b>Source temporarily unavailable</b><p>{source?.error||'The upstream provider did not return a usable response. Other source cards remain independent.'}</p></div>}
export default function WorldPulse(){
 const [country,setCountry]=useState('IND'),[lat,setLat]=useState(17.385),[lon,setLon]=useState(78.4867),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/data?action=world&country=${country}&lat=${lat}&lon=${lon}`,{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'World source failed');setData(d)}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[country,lat,lon]);
 const s=data?.sources||{};
 const useLoc=()=>navigator.geolocation?.getCurrentPosition(p=>{setLat(+p.coords.latitude.toFixed(5));setLon(+p.coords.longitude.toFixed(5))},e=>setError(`Location permission: ${e.message}`));
 return <div>
  <div className="grid2 worldControls"><div className="card pad"><div className="grid2"><div><label className="label">Country context</label><select className="select" value={country} onChange={e=>setCountry(e.target.value)}>{[['IND','India'],['USA','United States'],['CHN','China'],['GBR','United Kingdom'],['JPN','Japan'],['DEU','Germany'],['BRA','Brazil']].map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div><div><label className="label">Weather location</label><div className="pillRow"><button className="btn" onClick={useLoc}>Use my location</button><button className="btn primary" onClick={load} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div><p className="muted" style={{fontSize:11}}>Lat {lat} · Lon {lon}. Browser geolocation is optional.</p></div></div></div>
   <div className="card pad"><p className="eyebrow">Independent-source health</p><div className="sourceLine">{EXPECTED.map(([k,name])=>{const v=s[k];return <SourceStatus key={k} provider={v?.provenance?.provider||name} state={loading&&!data?'CHECKING':v?.ok?'CONNECTED':v?'DEGRADED':'CHECKING'}/>})}</div><p className="bodycopy compactCopy">{data?`${data.connected} of ${EXPECTED.length} source families connected; ${data.degraded} degraded at ${date(data.asOf)}.`:'Checking independent providers…'} A degraded provider does not blank or fabricate the others.</p></div></div>
  {error&&<div className="error" style={{marginTop:12}}><b>World pulse request failed.</b> {error}</div>}
  <div className="worldGrid" style={{marginTop:12}}>
   <div className="card worldCard"><p className="eyebrow">Weather</p><h3>Local physical state</h3>{loading&&!s.weather?<LoadingRows/>:s.weather?.ok?<div className="kv"><KV l="Temperature" v={`${num(s.weather.data.current?.temperature_2m,1)} °C`}/><KV l="Feels like" v={`${num(s.weather.data.current?.apparent_temperature,1)} °C`}/><KV l="Precipitation" v={`${num(s.weather.data.current?.precipitation,1)} mm`}/><KV l="Humidity" v={`${num(s.weather.data.current?.relative_humidity_2m,0)}%`}/><KV l="Wind" v={`${num(s.weather.data.current?.wind_speed_10m,1)} km/h`}/></div>:<FeedError source={s.weather}/>}</div>
   <div className="card worldCard"><p className="eyebrow">Macro</p><h3>{s.macro?.data?.[0]?.country||country}</h3>{loading&&!s.macro?<LoadingRows n={5}/>:s.macro?.ok?<div className="kv">{s.macro.data.map(x=><KV key={x.code} l={`${x.name} · ${x.date}`} v={x.unit==='people'?Math.round(x.value).toLocaleString():`${num(x.value,2)} ${x.unit}`}/>)}</div>:<FeedError source={s.macro}/>}</div>
   <div className="card worldCard"><p className="eyebrow">Rates</p><h3>U.S. Treasury curve</h3>{loading&&!s.rates?<LoadingRows/>:s.rates?.ok&&s.rates.data.latest?<div className="kv"><KV l="2 year" v={`${num(s.rates.data.latest.y2,2)}%`}/><KV l="5 year" v={`${num(s.rates.data.latest.y5,2)}%`}/><KV l="10 year" v={`${num(s.rates.data.latest.y10,2)}%`}/><KV l="30 year" v={`${num(s.rates.data.latest.y30,2)}%`}/><KV l="Date" v={String(s.rates.data.latest.date).slice(0,10)}/><MiniLine values={(s.rates.data.history||[]).map(x=>x.y10)} label="10-year Treasury yield · recent official business days"/></div>:<FeedError source={s.rates}/>}</div>
   <div className="card worldCard"><p className="eyebrow">Space weather</p><h3>Geomagnetic + solar wind</h3>{loading&&!s.spaceWeather?<LoadingRows/>:s.spaceWeather?.ok?<div className="kv"><KV l="Planetary Kp" v={num(s.spaceWeather.data.kIndex?.Kp??s.spaceWeather.data.kIndex?.kp,2)}/><KV l="Solar-wind speed" v={`${num(s.spaceWeather.data.solarWind?.proton_speed??s.spaceWeather.data.solarWind?.speed,1)} km/s`}/><KV l="Solar wind time" v={s.spaceWeather.data.solarWind?.time_tag||'—'}/><KV l="Recent alert rows" v={s.spaceWeather.data.alerts?.length||0}/></div>:<FeedError source={s.spaceWeather}/>}<p className="bodycopy" style={{fontSize:10}}>Displayed as separate physical context. It is not silently injected into a market forecast without target-specific validation.</p></div>
   <div className="card worldCard"><p className="eyebrow">Earthquakes</p><h3>Significant recent events</h3>{loading&&!s.earthquakes?<LoadingRows/>:s.earthquakes?.ok?<Events rows={s.earthquakes.data} render={x=><><b>M{num(x.mag,1)} · {x.place}</b><p>{date(x.time)}</p></>}/>:<FeedError source={s.earthquakes}/>}</div>
   <div className="card worldCard"><p className="eyebrow">NASA EONET</p><h3>Open natural events</h3>{loading&&!s.naturalEvents?<LoadingRows/>:s.naturalEvents?.ok?<Events rows={s.naturalEvents.data} render={x=><><b>{x.title}</b><p>{x.categories?.join(', ')||'Natural event'} · {x.geometry?.date?date(x.geometry.date):'current/open'}</p></>}/>:<FeedError source={s.naturalEvents}/>}</div>
   <div className="card worldCard"><p className="eyebrow">New CVEs</p><h3>NVD published window</h3>{loading&&!s.cyber?<LoadingRows/>:s.cyber?.ok?<Events rows={s.cyber.data} render={x=><><b>{x.id} · {x.severity||'unscored'} {x.score??''}</b><p>{x.description?.slice(0,150)}</p></>}/>:<FeedError source={s.cyber}/>}</div>
   <div className="card worldCard"><p className="eyebrow">Known exploited</p><h3>CISA KEV</h3>{loading&&!s.knownExploited?<LoadingRows/>:s.knownExploited?.ok?<Events rows={s.knownExploited.data} render={x=><><b>{x.cveID} · {x.vendorProject} {x.product}</b><p>Added {x.dateAdded} · due {x.dueDate} · ransomware {x.knownRansomwareCampaignUse}</p></>}/>:<FeedError source={s.knownExploited}/>}</div>
  </div>
 </div>
}
