import { fetchJson, fetchText, settle } from '../http.mjs';
export const PROV={
 weather:{provider:'Open-Meteo',family:'weather',cadence:'model/current updates',synthetic:false,rights:'Open-Meteo and underlying model terms apply'},
 earthquakes:{provider:'USGS',family:'earthquakes',cadence:'minute-updated summary feed',synthetic:false,rights:'U.S. government data; USGS terms apply'},
 natural:{provider:'NASA EONET',family:'natural events',cadence:'event-driven',synthetic:false,rights:'NASA event metadata; linked-source rights may differ'},
 macro:{provider:'World Bank Indicators',family:'macro + development',cadence:'series-specific',synthetic:false,rights:'World Bank API/source metadata terms apply'},
 rates:{provider:'U.S. Treasury',family:'rates',cadence:'business days',synthetic:false,rights:'Public Treasury data; site terms apply'},
 cyber:{provider:'NIST NVD',family:'cyber vulnerabilities',cadence:'continuously enriched',synthetic:false,rights:'NVD API terms/attribution apply; not endorsed or certified by NVD'},
 kev:{provider:'CISA KEV',family:'known exploited vulnerabilities',cadence:'event-driven',synthetic:false,rights:'U.S. government catalog'},
 space:{provider:'NOAA SWPC',family:'space weather',cadence:'minutes/product-specific',synthetic:false,rights:'U.S. government space-weather products'}
};
export async function weather(lat,lon){const u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',lat);u.searchParams.set('longitude',lon);u.searchParams.set('current','temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,rain,weather_code,cloud_cover,surface_pressure,wind_speed_10m,wind_direction_10m');u.searchParams.set('hourly','temperature_2m,precipitation_probability,precipitation,wind_speed_10m');u.searchParams.set('forecast_days','3');u.searchParams.set('timezone','auto');return fetchJson(u,{timeoutMs:8000,ttlMs:10*60_000});}
export async function earthquakes(){const d=await fetchJson('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_day.geojson',{timeoutMs:7000,ttlMs:60_000});return (d.features||[]).slice(0,20).map(x=>({id:x.id,title:x.properties?.title,mag:+x.properties?.mag,place:x.properties?.place,time:+x.properties?.time,url:x.properties?.url,coordinates:x.geometry?.coordinates}));}
export async function naturalEvents(){const d=await fetchJson('https://eonet.gsfc.nasa.gov/api/v3/events?status=open&limit=30',{timeoutMs:8000,ttlMs:10*60_000});return (d.events||[]).map(x=>({id:x.id,title:x.title,categories:(x.categories||[]).map(c=>c.title),sourceUrl:x.sources?.[0]?.url||null,geometry:x.geometry?.at(-1)||null}));}
const IND=[['NY.GDP.MKTP.KD.ZG','GDP growth','%'],['FP.CPI.TOTL.ZG','Inflation','%'],['SL.UEM.TOTL.ZS','Unemployment','%'],['NE.TRD.GNFS.ZS','Trade share of GDP','%'],['SP.POP.TOTL','Population','people'],['EG.USE.ELEC.KH.PC','Power use per person','kWh']];
export async function macro(country='IND'){const codes=IND.map(x=>x[0]).join(';');const d=await fetchJson(`https://api.worldbank.org/v2/country/${encodeURIComponent(country)}/indicator/${codes}?source=2&format=json&mrnev=3&per_page=100`,{timeoutMs:15000,ttlMs:6*60*60_000});const rows=Array.isArray(d?.[1])?d[1].filter(x=>x.value!=null):[],map=new Map();for(const r of rows){const k=r.indicator?.id;if(!k)continue;if(!map.has(k))map.set(k,[]);map.get(k).push(r);}return IND.map(([code,name,unit])=>{const s=(map.get(code)||[]).sort((a,b)=>String(b.date).localeCompare(String(a.date)));return s[0]?{code,name,unit,value:+s[0].value,date:s[0].date,country:s[0].country?.value,history:s.slice(0,3).map(r=>({date:r.date,value:+r.value}))}:null;}).filter(Boolean);}
function tag(block,n){return block.match(new RegExp(`<d:${n}[^>]*>([^<]*)<\\/d:${n}>`,'i'))?.[1]||null;}
export async function rates(){const y=new Date().getUTCFullYear(),xml=await fetchText(`https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data=daily_treasury_yield_curve&field_tdr_date_value=${y}`,{timeoutMs:9000,ttlMs:60*60_000,headers:{Accept:'application/xml,text/xml,*/*'}});const rows=[...xml.matchAll(/<m:properties>([\s\S]*?)<\/m:properties>/gi)].map(m=>m[1]).map(b=>({date:tag(b,'NEW_DATE'),m1:+tag(b,'BC_1MONTH'),m3:+tag(b,'BC_3MONTH'),m6:+tag(b,'BC_6MONTH'),y1:+tag(b,'BC_1YEAR'),y2:+tag(b,'BC_2YEAR'),y5:+tag(b,'BC_5YEAR'),y10:+tag(b,'BC_10YEAR'),y20:+tag(b,'BC_20YEAR'),y30:+tag(b,'BC_30YEAR')})).filter(x=>x.date).sort((a,b)=>xdate(a).localeCompare(xdate(b)));return{latest:rows.at(-1)||null,history:rows.slice(-40)};}
function xdate(x){return String(x.date||'');}
export async function cyber(){const end=new Date(),start=new Date(end-7*86400000);const iso=d=>d.toISOString().replace('Z','');const u=new URL('https://services.nvd.nist.gov/rest/json/cves/2.0');u.searchParams.set('pubStartDate',iso(start));u.searchParams.set('pubEndDate',iso(end));u.searchParams.set('resultsPerPage','40');const d=await fetchJson(u,{timeoutMs:9000,ttlMs:15*60_000});return (d.vulnerabilities||[]).map(x=>{const c=x.cve||{},m=c.metrics||{},v=m.cvssMetricV31?.[0]?.cvssData||m.cvssMetricV30?.[0]?.cvssData||m.cvssMetricV2?.[0]?.cvssData||{};return{id:c.id,published:c.published,lastModified:c.lastModified,score:v.baseScore??null,severity:v.baseSeverity??null,description:c.descriptions?.find(z=>z.lang==='en')?.value||'',url:`https://nvd.nist.gov/vuln/detail/${c.id}`};}).filter(x=>!x.description.toLowerCase().startsWith('rejected reason')).sort((a,b)=>String(b.published).localeCompare(String(a.published))).slice(0,25);}
export async function kev(){const d=await fetchJson('https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json',{timeoutMs:8000,ttlMs:20*60_000});return (d.vulnerabilities||[]).sort((a,b)=>String(b.dateAdded).localeCompare(String(a.dateAdded))).slice(0,15).map(v=>({cveID:v.cveID,vendorProject:v.vendorProject,product:v.product,vulnerabilityName:v.vulnerabilityName,dateAdded:v.dateAdded,shortDescription:v.shortDescription,dueDate:v.dueDate,knownRansomwareCampaignUse:v.knownRansomwareCampaignUse}));}
function latestK(raw){if(Array.isArray(raw)){const last=raw.at(-1);if(last&&typeof last==='object'&&!Array.isArray(last))return last;if(Array.isArray(raw[0])&&Array.isArray(last))return Object.fromEntries(raw[0].map((h,i)=>[h,last[i]]));}return raw&&typeof raw==='object'?raw:{};}
export async function spaceWeather(){const [kp,wind,alerts]=await Promise.all([fetchJson('https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json',{timeoutMs:7000,ttlMs:5*60_000}),fetchJson('https://services.swpc.noaa.gov/products/summary/solar-wind-speed.json',{timeoutMs:7000,ttlMs:5*60_000}),fetchJson('https://services.swpc.noaa.gov/products/alerts.json',{timeoutMs:7000,ttlMs:5*60_000})]);return{kIndex:latestK(kp),solarWind:Array.isArray(wind)?wind.at(-1):wind,alerts:Array.isArray(alerts)?alerts.slice(-8).reverse():[]};}
export async function pulse({lat=17.385,lon=78.4867,country='IND'}={}){const jobs=await Promise.all([settle('weather',PROV.weather,()=>weather(lat,lon)),settle('earthquakes',PROV.earthquakes,earthquakes),settle('naturalEvents',PROV.natural,naturalEvents),settle('macro',PROV.macro,()=>macro(country)),settle('rates',PROV.rates,rates),settle('cyber',PROV.cyber,cyber),settle('knownExploited',PROV.kev,kev),settle('spaceWeather',PROV.space,spaceWeather)]);return{asOf:new Date().toISOString(),location:{lat,lon},country,sources:Object.fromEntries(jobs.map(x=>[x.name,x])),connected:jobs.filter(x=>x.ok).length,degraded:jobs.filter(x=>!x.ok).length};}
