import Footer from '@/app/components/Footer';

const deliverables=[
 ['Market state','Price/NAV/reference value, timing, source, OHLC history, volume where published, market state and data freshness.','⌁'],
 ['Forecast distribution','Five forward checkpoints, center path, directional probability and empirical 50/80/90% uncertainty ranges.','∿'],
 ['Evidence + validation','Effective historical examples, walk-forward checks, direction accuracy, median error, interval coverage and calibration.','◎'],
 ['Mechanics + technical context','RSI, ATR scale, realized volatility, range position, moving-average distance and venue microstructure where actually available.','≋'],
 ['World + event evidence','Macro, rates, local weather, natural events, earthquakes, cyber risk, known exploits and space weather kept source-isolated.','◉'],
 ['Research workflow','Watchlists, recurring-investment simulation, CSV/JSON export, news/filings research and a limited scenario sandbox.','◇']
];

export default function Home(){return <div className="page overviewPage">
 <section className="overviewHero">
  <div className="card heroMain overviewLead"><p className="eyebrow">Zachitan v4 research beta</p><h1 className="heroTitle">Markets, forecasts and the evidence around them.</h1><p className="heroCopy">A source-first research terminal for stocks, ETFs, mutual funds, SIP histories, indices, futures, FX, crypto and best-effort options—joined to validation, world data, news and simulation without pretending every feed is real-time.</p><div className="pillRow heroActions"><a className="btn primary" href="/markets">Open market lab</a><a className="btn" href="/watchlist">Build watchlist</a><a className="btn" href="/world">Open world pulse</a></div><div className="overviewStats"><div><b>8</b><span>market / research classes</span></div><div><b>5</b><span>forward forecast checkpoints</span></div><div><b>3</b><span>public uncertainty bands</span></div><div><b>8</b><span>independent world source families</span></div></div></div>
  <aside className="card overviewVisual" aria-label="Zachitan output structure illustration"><div className="visualTop"><span>OUTPUT ANATOMY</span><b>Source → evidence → distribution</b></div><div className="visualChart"><div className="historyTrace"><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="forecastFan"><span className="fan90"/><span className="fan80"/><span className="fan50"/><span className="fanPath"/><b className="p1">1</b><b className="p2">2</b><b className="p3">3</b><b className="p4">4</b><b className="p5">5</b></div></div><div className="visualLegend"><span><i className="legendObserved"/>Observed history</span><span><i className="legendForecast"/>Forecast path</span><span><i className="legendRange"/>Uncertainty</span></div><div className="visualMeters"><div><span>Evidence</span><em><i style={{width:'76%'}}/></em></div><div><span>Calibration</span><em><i style={{width:'64%'}}/></em></div><div><span>Source freshness</span><em><i style={{width:'88%'}}/></em></div></div><p className="visualNote">Illustration of the interface structure, not market data or a current forecast.</p></aside>
 </section>

 <section className="section"><div className="sectionHead"><div><p className="eyebrow">What the terminal delivers</p><h2>One instrument, multiple layers of evidence</h2></div><p>Each layer answers a different research question. Missing or gated data stays visibly missing instead of being replaced with synthetic values.</p></div><div className="deliverableGrid">{deliverables.map(([h,p,g])=><div className="card deliverable" key={h}><div className="deliverableGlyph">{g}</div><div><h3>{h}</h3><p>{p}</p></div></div>)}</div></section>

 <section className="section"><div className="card researchCanvas"><div className="canvasHead"><div><p className="eyebrow">Research surfaces</p><h2>From raw observation to something you can inspect</h2></div><span className="betaBadge">NO TRADE EXECUTION</span></div><div className="canvasGrid"><a href="/markets" className="canvasCell"><span>01</span><b>Markets</b><p>Interactive candles, source timing, forecasts, checkpoints, validation, options and raw observations.</p><div className="miniBars"><i/><i/><i/><i/><i/><i/></div></a><a href="/world" className="canvasCell"><span>02</span><b>World pulse</b><p>Independent physical, macro, rate and cyber sources with per-provider health instead of one combined black box.</p><div className="dotMatrix">{Array.from({length:16},(_,i)=><i key={i}/>)}</div></a><a href="/news" className="canvasCell"><span>03</span><b>News + filings</b><p>Publisher-attributed reporting plus official filing pathways, with compliance gates stated as gates.</p><div className="lineStack"><i/><i/><i/><i/></div></a><a href="/watchlist" className="canvasCell"><span>04</span><b>Watchlist</b><p>Cross-asset saved instruments, refreshable research snapshots and local export.</p><div className="watchMini"><i/><i/><i/></div></a><a href="/playground" className="canvasCell"><span>05</span><b>Playground</b><p>Restricted public scenario controls for understanding sensitivity without exposing production engineering.</p><div className="sliderMini"><i/><i/><i/></div></a><a href="/methodology" className="canvasCell"><span>06</span><b>Methodology</b><p>Public architecture, uncertainty and validation concepts without internal weights, transforms or ranking implementation.</p><div className="nodeMini"><i/><i/><i/><i/></div></a></div></div></section>

 <section className="section"><div className="sectionHead"><div><p className="eyebrow">Coverage</p><h2>Multi-asset by design</h2></div><p>Coverage is determined by actual connected providers and the rights/timing of each feed, not by a marketing label.</p></div><div className="coverageStrip">{[['Stocks + ETFs','Global publisher-covered equities and ETFs'],['Funds + SIP','Fund/NAV history and recurring-investment replay'],['Indices + futures','Index and futures OHLC histories'],['FX','Publisher pairs plus official ECB reference series'],['Crypto','Coinbase live ticker and public venue microstructure'],['Options','Best-effort published chains when upstream access permits'],['World data','Macro, rates, physical and cyber evidence'],['News + filings','Reporting plus official primary-disclosure pathways']].map(([h,p])=><div className="coverageItem" key={h}><b>{h}</b><span>{p}</span></div>)}</div></section>

 <section className="section"><div className="grid3"><div className="card pad"><p className="eyebrow">Truth contract</p><h3>Observed, inferred and unavailable stay separate.</h3><p className="bodycopy">A delayed quote is labelled delayed. An official reference rate is labelled a reference rate. A forecast is labelled experimental. A blocked or licensed feed is not silently replaced.</p></div><div className="card pad"><p className="eyebrow">Chart + prediction</p><h3>Inspect the path, not just one target.</h3><p className="bodycopy">Pan and zoom observed history, inspect OHLC with the crosshair, then compare the five projected checkpoints against the width and calibration of their uncertainty bands.</p></div><div className="card pad"><p className="eyebrow">Research beta</p><h3>Useful information without a guarantee.</h3><p className="bodycopy">Zachitan is still experimental research software. It does not execute trades, guarantee outcomes or convert probabilistic analysis into personalized financial advice.</p></div></div></section>
 <Footer/>
 </div>}
