export const PRESETS=[
 {symbol:'BTC-USD',name:'Bitcoin / US Dollar',assetClass:'crypto',provider:'coinbase',exchange:'Coinbase'},
 {symbol:'ETH-USD',name:'Ethereum / US Dollar',assetClass:'crypto',provider:'coinbase',exchange:'Coinbase'},
 {symbol:'AAPL',name:'Apple',assetClass:'stock',provider:'yahoo',exchange:'NASDAQ'},
 {symbol:'MSFT',name:'Microsoft',assetClass:'stock',provider:'yahoo',exchange:'NASDAQ'},
 {symbol:'NVDA',name:'NVIDIA',assetClass:'stock',provider:'yahoo',exchange:'NASDAQ'},
 {symbol:'RELIANCE.NS',name:'Reliance Industries',assetClass:'stock',provider:'yahoo',exchange:'NSE'},
 {symbol:'TCS.NS',name:'Tata Consultancy Services',assetClass:'stock',provider:'yahoo',exchange:'NSE'},
 {symbol:'SPY',name:'SPDR S&P 500 ETF',assetClass:'etf',provider:'yahoo',exchange:'NYSE Arca'},
 {symbol:'QQQ',name:'Invesco QQQ',assetClass:'etf',provider:'yahoo',exchange:'NASDAQ'},
 {symbol:'NIFTYBEES.NS',name:'Nippon India ETF Nifty BeES',assetClass:'etf',provider:'yahoo',exchange:'NSE'},
 {symbol:'^GSPC',name:'S&P 500',assetClass:'index',provider:'yahoo',exchange:'S&P DJI'},
 {symbol:'^IXIC',name:'NASDAQ Composite',assetClass:'index',provider:'yahoo',exchange:'NASDAQ'},
 {symbol:'^NSEI',name:'NIFTY 50',assetClass:'index',provider:'yahoo',exchange:'NSE'},
 {symbol:'^BSESN',name:'S&P BSE SENSEX',assetClass:'index',provider:'yahoo',exchange:'BSE'},
 {symbol:'ES=F',name:'E-mini S&P 500 Futures',assetClass:'future',provider:'yahoo',exchange:'CME'},
 {symbol:'NQ=F',name:'E-mini Nasdaq-100 Futures',assetClass:'future',provider:'yahoo',exchange:'CME'},
 {symbol:'GC=F',name:'Gold Futures',assetClass:'future',provider:'yahoo',exchange:'COMEX'},
 {symbol:'CL=F',name:'Crude Oil Futures',assetClass:'future',provider:'yahoo',exchange:'NYMEX'},
 {symbol:'EURUSD=X',name:'EUR / USD',assetClass:'forex',provider:'yahoo',exchange:'FX'},
 {symbol:'USDINR=X',name:'USD / INR',assetClass:'forex',provider:'yahoo',exchange:'FX'},
 {symbol:'GBPUSD=X',name:'GBP / USD',assetClass:'forex',provider:'yahoo',exchange:'FX'},
 {symbol:'EUR/USD',name:'EUR / USD official reference',assetClass:'forex',provider:'ecb',exchange:'ECB'},
 {symbol:'EUR/INR',name:'EUR / INR official reference',assetClass:'forex',provider:'ecb',exchange:'ECB'},
 {symbol:'EUR/GBP',name:'EUR / GBP official reference',assetClass:'forex',provider:'ecb',exchange:'ECB'},
 {symbol:'VFIAX',name:'Vanguard 500 Index Fund Admiral',assetClass:'mutual_fund',provider:'yahoo',exchange:'Fund'},
 {symbol:'FXAIX',name:'Fidelity 500 Index Fund',assetClass:'mutual_fund',provider:'yahoo',exchange:'Fund'}
];
export const SOURCE_LEDGER=[
 {name:'Coinbase Exchange',state:'connected',classes:'Crypto',role:'Native live ticker, candles, order book and recent trades.',quality:'Exchange-native public endpoints.',rights:'Coinbase terms apply.'},
 {name:'Yahoo Finance public chart feed',state:'connected-best-effort',classes:'Stocks, ETFs, global mutual funds, indices, futures, forex, option contracts',role:'Broad market OHLC data and publisher metadata.',quality:'Real publisher data; timing can be real-time, delayed or end-of-day by market.',rights:'Undocumented publisher endpoint; Yahoo terms apply. Not an exchange entitlement.'},
 {name:'AMFI',state:'connected',classes:'Indian mutual funds',role:'Official latest and historical scheme NAV.',quality:'NAV is end-of-day, not intraday.',rights:'AMFI/AMC publication terms apply.'},
 {name:'ECB Data Portal',state:'connected',classes:'FX reference rates',role:'Official working-day EUR reference rates.',quality:'Reference rate, not executable intraday FX quote.',rights:'ECB terms apply.'},
 {name:'Yahoo options session',state:'best-effort',classes:'US listed options',role:'Option-chain view when Yahoo session/crumb access succeeds.',quality:'May be delayed; not an OPRA entitlement.',rights:'Yahoo terms apply.'},
 {name:'Alpha Vantage / Twelve Data',state:'optional-key',classes:'Global market backup + licensed tiers',role:'Provider adapter slot for stronger contractual coverage.',quality:'Requires a legitimate API key and plan appropriate to intended use.',rights:'Provider plan/redistribution terms apply.'},
 {name:'Open-Meteo',state:'connected',classes:'Weather',role:'Current weather + short forecast context.',quality:'Forecast model aggregation.',rights:'Open-Meteo/underlying model terms.'},
 {name:'World Bank',state:'connected',classes:'Macro',role:'Growth, inflation, employment, trade, population, power use.',quality:'Slow-moving official/compiled indicators.',rights:'World Bank/source metadata terms.'},
 {name:'U.S. Treasury',state:'connected',classes:'Rates',role:'Official Treasury yield curve.',quality:'Business-day official data.',rights:'U.S. Treasury terms.'},
 {name:'USGS + NASA EONET',state:'connected',classes:'Earth hazards',role:'Earthquakes, storms, fires and natural events.',quality:'Official/public event feeds.',rights:'USGS/NASA terms.'},
 {name:'NIST NVD + CISA KEV',state:'connected',classes:'Cyber risk',role:'New CVEs and known-exploited vulnerabilities.',quality:'Public government cybersecurity feeds.',rights:'NVD/CISA terms.'},
 {name:'NOAA SWPC',state:'connected',classes:'Space weather',role:'Geomagnetic K-index, solar wind and alerts.',quality:'Physical evidence only; not silently injected into price forecasts.',rights:'NOAA terms.'},
 {name:'SEC EDGAR',state:'gated-contact',classes:'Company filings',role:'Official U.S. filing connector.',quality:'Accurate official filing source once operator contact is configured.',rights:'SEC automated access policy requires a declared contact.'},
 {name:'Licensed exchange feeds',state:'gated-license',classes:'Exchange-entitled real-time equities, futures, indices, options',role:'Production-grade entitlement layer.',quality:'Not fabricated or bypassed in this beta.',rights:'Exchange/vendor licenses required.'}
];
