const EPS=1e-12;
export const clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
export const sum=a=>a.reduce((s,x)=>s+x,0);
export const mean=a=>a.length?sum(a)/a.length:NaN;
export function quantile(v,q){const a=v.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return NaN;const p=clamp(q,0,1)*(a.length-1),lo=Math.floor(p),hi=Math.ceil(p);return lo===hi?a[lo]:a[lo]+(a[hi]-a[lo])*(p-lo);}
export const median=a=>quantile(a,.5);
export function stdev(a){if(!a.length)return NaN;const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)));}
export function mad(a){const m=median(a);return median(a.map(x=>Math.abs(x-m)));}
export function robustZ(x,a){const m=median(a),d=mad(a);return Number.isFinite(m)&&Number.isFinite(d)&&d>EPS?(x-m)/(1.4826*d+EPS):0;}
export function weightedQuantile(values,weights,q){const a=values.map((v,i)=>({v,w:Math.max(0,weights[i]||0)})).filter(x=>Number.isFinite(x.v)&&x.w>0).sort((x,y)=>x.v-y.v);if(!a.length)return NaN;const t=sum(a.map(x=>x.w))*clamp(q,0,1);let c=0;for(const x of a){c+=x.w;if(c>=t)return x.v;}return a.at(-1).v;}
function normalize(w){const s=sum(w);return s>EPS?w.map(x=>x/s):w.map(()=>1/w.length);}
function ess(w){const n=normalize(w);return 1/Math.max(EPS,sum(n.map(x=>x*x)));}
function logret(c,i,k){return i>=k&&c[i-k]>0&&c[i]>0?Math.log(c[i]/c[i-k]):NaN;}
function rsiAt(c,i,p=14){if(i<p)return NaN;let g=0,l=0;for(let j=i-p+1;j<=i;j++){const d=c[j]-c[j-1];if(d>=0)g+=d;else l-=d;}return l<EPS?100:100-100/(1+(g/p)/(l/p));}
function atrAt(cs,i,p=14){if(i<p)return NaN;let s=0;for(let j=i-p+1;j<=i;j++){const prev=cs[j-1]?.close??cs[j].close;s+=Math.max(cs[j].high-cs[j].low,Math.abs(cs[j].high-prev),Math.abs(cs[j].low-prev));}return s/p;}
function volAt(c,i,p){const a=[];for(let j=Math.max(1,i-p+1);j<=i;j++)if(c[j-1]>0&&c[j]>0)a.push(Math.log(c[j]/c[j-1]));return a.length>=5?stdev(a):0;}
function avgAt(c,i,p){if(i<p-1)return NaN;return mean(c.slice(i-p+1,i+1));}
function feature(candles,i){if(i<65)return null;const c=candles.map(x=>x.close),v=candles.map(x=>x.volume||0),now=c[i],hi=Math.max(...candles.slice(i-39,i+1).map(x=>x.high)),lo=Math.min(...candles.slice(i-39,i+1).map(x=>x.low));const a20=avgAt(c,i,20),a50=avgAt(c,i,50),atr=atrAt(candles,i,14);const vz=robustZ(v[i],v.slice(Math.max(0,i-40),i));const f=[logret(c,i,3),logret(c,i,10),logret(c,i,25),volAt(c,i,10),volAt(c,i,30),(rsiAt(c,i,14)-50)/50,Math.log(now/a20),Math.log(now/a50),atr/now,vz,(now-lo)/(hi-lo+EPS)-.5];return f.every(Number.isFinite)?f:null;}
function robustScale(rows,current){const d=current.length,med=[],scale=[];for(let j=0;j<d;j++){const x=rows.map(r=>r.features[j]);med[j]=median(x);scale[j]=1.4826*mad(x)||stdev(x)||1;}const z=f=>f.map((x,j)=>(x-med[j])/(scale[j]+EPS));return{rows:rows.map(r=>({...r,z:z(r.features)})),current:z(current)};}
const featureWeights=[1.15,1.05,.9,1.1,1.0,.8,.9,.75,.85,.6,.75];
function distance(a,b){let s=0;for(let i=0;i<a.length;i++)s+=featureWeights[i]*(a[i]-b[i])**2;return Math.sqrt(s);}
function capWeights(weights,cap=.055){let w=normalize(weights);for(let iter=0;iter<5;iter++){let excess=0;w=w.map(x=>{if(x>cap){excess+=x-cap;return cap;}return x;});const free=sum(w.map(x=>x<cap?x:0));if(excess<EPS||free<EPS)break;w=w.map(x=>x<cap?x+excess*(x/free):x);}return normalize(w);}
export function buildSamples(candles,horizon){if(!Array.isArray(candles)||candles.length<170||horizon<1)return{samples:[],effectiveN:0};const last=candles.length-1,cur=feature(candles,last);if(!cur)return{samples:[],effectiveN:0};const rows=[];for(let i=70;i+horizon<last;i++){const f=feature(candles,i);if(!f)continue;const base=candles[i].close;if(!(base>0))continue;const path=[];let ok=true;for(let k=1;k<=horizon;k++){const px=candles[i+k].close;if(!(px>0)){ok=false;break;}path.push(Math.log(px/base));}if(ok)rows.push({i,features:f,path,terminal:path.at(-1)});}if(rows.length<70)return{samples:[],effectiveN:0};const s=robustScale(rows,cur);let near=s.rows.map(r=>({...r,d:distance(r.z,s.current)})).sort((a,b)=>a.d-b.d).slice(0,Math.min(320,Math.max(90,Math.floor(s.rows.length*.35))));const ds=median(near.map(x=>x.d))||1;const raw=near.map(r=>{const kernel=Math.exp(-.5*(r.d/(ds+EPS))**2);const age=last-r.i;const recency=Math.pow(.5,age/Math.max(250,candles.length*.55));return kernel*(.55+.45*recency);});const w=capWeights(raw);const samples=near.map((r,i)=>({...r,weight:w[i]}));return{samples,effectiveN:ess(w)};}
function prob(s,p){return sum(s.filter(p).map(x=>x.weight));}
function rangeFor(values,weights,coverage,effectiveN){const alpha=1-coverage,min=Math.ceil(2/Math.max(alpha,.005));if(effectiveN<min)return null;return[weightedQuantile(values,weights,alpha/2),weightedQuantile(values,weights,1-alpha/2)];}
function checkpointBars(h){const xs=[];for(let i=1;i<=5;i++)xs.push(Math.max(1,Math.round(h*i/5)));return[...new Set(xs)];}
function calibrationScore(v){if(!v?.available)return 35;const dir=Number.isFinite(v.directionAccuracy)?Math.max(0,1-Math.abs(v.directionAccuracy-.5)/.5):0;const err=Number.isFinite(v.medianAbsPctError)?Math.exp(-v.medianAbsPctError*18):0;const cov=v.coverage?.[80] == null ? .5 : Math.exp(-Math.abs(v.coverage[80]-.8)*3);return clamp(Math.round(100*(.35*err+.25*dir+.4*cov)),0,100);}
export function forecast(candles,horizon=12,validation=null){const current=candles?.at(-1)?.close;if(!(current>0))return{available:false,reason:'No valid current price'};const {samples,effectiveN}=buildSamples(candles,horizon);if(!samples.length)return{available:false,reason:'Not enough clean history for this timeframe.',effectiveN:0};const w=samples.map(x=>x.weight),terminal=samples.map(x=>x.terminal);const qp=(arr,q)=>current*Math.exp(weightedQuantile(arr,w,q));const rawMedian=weightedQuantile(terminal,w,.5);const evidenceBase=clamp((effectiveN-10)/60,0,1);const shrink=.35+.65*evidenceBase;const center=current*Math.exp(rawMedian*shrink);const ranges={};for(const c of [50,80,90,95,99]){const r=rangeFor(terminal,w,c/100,effectiveN);ranges[c]=r?r.map(x=>current*Math.exp(x)):null;}
 const points=checkpointBars(horizon).map(bar=>{const vals=samples.map(x=>x.path[Math.min(bar,x.path.length)-1]);const med=weightedQuantile(vals,w,.5)*shrink;const r50=rangeFor(vals,w,.50,effectiveN),r80=rangeFor(vals,w,.80,effectiveN),r90=rangeFor(vals,w,.90,effectiveN);return{bar,price:current*Math.exp(med),change:Math.expm1(med),pUp:prob(samples,x=>x.path[Math.min(bar,x.path.length)-1]>0),ranges:{50:r50?.map(x=>current*Math.exp(x))||null,80:r80?.map(x=>current*Math.exp(x))||null,90:r90?.map(x=>current*Math.exp(x))||null}};});
 const look=candles.slice(Math.max(0,candles.length-61),-1),res=Math.max(...look.map(x=>x.high)),sup=Math.min(...look.map(x=>x.low)),upR=Math.max(0,Math.log(res/current)),dnR=Math.min(0,Math.log(sup/current));const pBreakUp=prob(samples,x=>x.path.some(r=>r>=upR)),pBreakDown=prob(samples,x=>x.path.some(r=>r<=dnR));const maxWeight=Math.max(...w),neighborQuality=clamp(1-maxWeight/.055,0,1);const validationQuality=calibrationScore(validation)/100;const evidenceScore=Math.round(100*clamp(.55*evidenceBase+.2*neighborQuality+.25*validationQuality,0,1));
 return{available:true,current,center,effectiveN,sampleCount:samples.length,evidenceScore,calibrationScore:Math.round(validationQuality*100),direction:{up:prob(samples,x=>x.terminal>0),down:prob(samples,x=>x.terminal<0)},ranges,points,breakout:{resistance:res,support:sup,up:pBreakUp,down:pBreakDown},risk:{dispersion:Math.expm1(stdev(terminal)||0),tailDown:current*Math.exp(weightedQuantile(terminal,w,.05)),tailUp:current*Math.exp(weightedQuantile(terminal,w,.95))}};}
export function validate(candles,horizon=12,maxChecks=50){if(!Array.isArray(candles)||candles.length<280+horizon)return{available:false,checks:0,reason:'Need more chronological history.'};const last=candles.length-horizon-1,start=Math.max(190,last-maxChecks*Math.max(2,Math.floor(horizon/2))),span=last-start,step=Math.max(1,Math.floor(span/maxChecks));const rec=[];for(let i=start;i<=last&&rec.length<maxChecks;i+=step){const prefix=candles.slice(0,i+1);const f=forecast(prefix,horizon,null);if(!f.available)continue;const actual=candles[i+horizon].close,now=candles[i].close,pred=f.center;if(!(actual>0&&now>0&&pred>0))continue;const pr=Math.log(pred/now),ar=Math.log(actual/now);rec.push({err:Math.abs(Math.log(actual/pred)),dir:Math.sign(pr)!==0&&Math.sign(pr)===Math.sign(ar),confidence:Math.max(f.direction.up,f.direction.down),ranges:f.ranges,actual});}
 if(rec.length<18)return{available:false,checks:rec.length,reason:'Too few clean walk-forward checks.'};const coverage={};for(const c of[50,80,90]){const rows=rec.filter(r=>r.ranges[c]);coverage[c]=rows.length?mean(rows.map(r=>r.actual>=r.ranges[c][0]&&r.actual<=r.ranges[c][1]?1:0)):null;}const high=rec.filter(r=>r.confidence>=.62);return{available:true,checks:rec.length,medianAbsPctError:Math.expm1(median(rec.map(r=>r.err))),directionAccuracy:mean(rec.map(r=>r.dir?1:0)),selectiveAccuracy:high.length>=5?mean(high.map(r=>r.dir?1:0)):null,selectiveCoverage:high.length/rec.length,coverage};}
export function indicators(candles){const i=candles.length-1,c=candles.map(x=>x.close),vol=candles.map(x=>x.volume||0),r14=rsiAt(c,i,14),atr=atrAt(candles,i,14),ret1=logret(c,i,1),ret5=logret(c,i,5),rv20=volAt(c,i,20),sma20=avgAt(c,i,20),sma50=avgAt(c,i,50),high52=Math.max(...candles.slice(Math.max(0,i-252),i+1).map(x=>x.high)),low52=Math.min(...candles.slice(Math.max(0,i-252),i+1).map(x=>x.low));return{rsi14:r14,atr14:atr,atrPct:atr/c[i],return1:ret1,return5:ret5,realizedVol20:rv20,sma20,sma50,distanceSma20:c[i]/sma20-1,distanceSma50:c[i]/sma50-1,volumeZ:robustZ(vol[i],vol.slice(Math.max(0,i-40),i)),high52,low52,position52:(c[i]-low52)/(high52-low52+EPS)};}
export function microstructure(book,trades){const bs=sum((book?.bids||[]).map(x=>x.size)),as=sum((book?.asks||[]).map(x=>x.size)),imb=(bs-as)/(bs+as+EPS),bid=book?.bids?.[0]?.price,ask=book?.asks?.[0]?.price,mid=Number.isFinite(bid)&&Number.isFinite(ask)?(bid+ask)/2:NaN,spread=Number.isFinite(mid)?(ask-bid)/mid*10000:NaN;let buy=0,sell=0;for(const t of trades||[]){const n=(t.price||0)*(t.size||0);if(t.makerSide==='sell')buy+=n;else if(t.makerSide==='buy')sell+=n;}return{bookImbalance:imb,tradeImbalance:(buy-sell)/(buy+sell+EPS),bestBid:bid,bestAsk:ask,spreadBps:spread,aggressiveBuy:buy,aggressiveSell:sell};}
