import Footer from '@/app/components/Footer';
export default function Page(){return <div className="page"><article className="legal"><p className="eyebrow">Privacy notice · Zachitan v4 research beta</p><h1>Privacy</h1><p><b>Operator:</b> Aphelion Private Limited, Telangana, India. Contact: <a href="mailto:dharan@aphelion.life">dharan@aphelion.life</a>.</p><p>This notice describes the current public research beta and the founding-access intake flow. Zachitan v4 intentionally minimizes account-level collection: no sign-in is required to use the public market, world, news, methodology, source or playground screens.</p>
<h2>Information stored in your browser</h2><p>Watchlists, local profile settings and research notes are stored using browser local storage on your device. In the current beta they are not synchronized to a Zachitan account database. Clearing site data may delete them.</p>
<h2>Founding-access requests</h2><p>The commercial workspace links to a Tally form used to collect contact information, organization/project context, the requested founding offer, research objective, dataset description, jurisdiction, data-rights confirmation and desired deliverable. Do not submit broker credentials, passwords, API secrets or datasets through that form. Tally processes form responses under its own service/privacy terms. Responses are used to assess scope, data-rights fit, delivery feasibility and follow-up before payment instructions are sent.</p>
<h2>Information processed when you use the site</h2><p>Normal web infrastructure can process technical request information such as IP address, user-agent, requested path, timestamps, performance/error metadata and security logs. Vercel currently hosts the public beta and may process infrastructure data under its own terms and privacy practices.</p>
<h2>Location</h2><p>The World screen uses a fixed Hyderabad starting point until you choose “Use my location.” Browser geolocation is opt-in. When you grant permission, latitude and longitude are used to request location-relevant weather context. Zachitan v4 does not intentionally persist that coordinate in a user profile database.</p>
<h2>Market, news and world providers</h2><p>The public research application makes server-side requests to data providers such as Coinbase, Yahoo Finance publisher endpoints, AMFI, ECB, Open-Meteo, World Bank, U.S. Treasury, USGS, NASA EONET, NIST NVD, CISA, NOAA SWPC, GDELT/Google News and—when properly configured—SEC EDGAR. The commercial build disables Zachitan's general provider aggregation route and instead prioritizes customer-supplied data. External links you open are governed by the destination’s privacy practices.</p>
<h2>No sale of personal data</h2><p>The beta and founding intake do not include a data-broker sale workflow or user-level behavioral advertising marketplace. If Zachitan later introduces accounts, subscriptions, personalization, analytics or advertising, this notice must be updated before those data uses are relied on.</p>
<h2>Security and retention</h2><p>We aim to minimize data retained by the application and use platform security controls, HTTPS and restricted permissions. No internet service can promise absolute security. Infrastructure logs and Tally form responses may be retained according to the applicable platform settings and provider policies. Browser-local data remains until you or the browser removes it.</p>
<h2>Your choices</h2><ul><li>Do not grant geolocation permission if you do not want location-based weather context.</li><li>Remove watchlists and profile data from the Profile/Watchlist screens or clear site storage.</li><li>Do not submit a founding-access request if you do not want the intake information processed for follow-up.</li><li>Contact <a href="mailto:dharan@aphelion.life">dharan@aphelion.life</a> for privacy questions.</li></ul>
<h2>India and other jurisdictions</h2><p>Zachitan is being developed in India. Privacy obligations can vary by jurisdiction. The project will update its notices, consent, rights-request and data-governance workflows as features involving persistent personal data are introduced. This notice is not a claim that every future regulatory requirement has already been implemented.</p>
<p><b>Effective:</b> 13 September 2026. <b>Version:</b> Zachitan v4 research beta + founding access.</p></article><Footer/></div>}
