import Footer from '@/app/components/Footer';
import { RELEASE_LINE } from '@/lib/release.mjs';

export default function Page(){return <div className="page"><div className="legal" style={{maxWidth:1100}}><p className="eyebrow">Public methodology · {RELEASE_LINE}</p><h1 style={{fontSize:58,letterSpacing:'-.065em',margin:'0 0 18px'}}>How Zachitan builds, tests and withholds an experimental forecast.</h1><p className="bodycopy" style={{fontSize:17}}>Zachitan {RELEASE_LINE} is a source-first empirical forecasting research system. The implementation is inspectable, so this page describes the actual publication contract: observed data, model output, validation evidence and untouched qualification remain distinct, and a numeric target is withheld when any required gate fails.</p>
 <section className="section"><div className="flow"><div className="flowStep"><b>Observe</b><p>Pull chronological observations with provider, timestamp, timing and rights metadata.</p></div><div className="flowStep"><b>Qualify data</b><p>Reject malformed OHLC rows, de-duplicate observations, preserve source timing and distinguish expected exchange closures from unexpected gaps.</p></div><div className="flowStep"><b>Represent</b><p>Represent market state using returns, volatility, RSI, moving-average distance, ATR, volume anomaly and rolling-range position.</p></div><div className="flowStep"><b>Ensemble</b><p>Combine unchanged-price, momentum, regime and analogue candidates using weights learned only from earlier completed validation origins, with disagreement shrinkage.</p></div><div className="flowStep"><b>Walk forward</b><p>Rebuild old forecasts using only information available at each chronological origin and compare them with later observations and naïve baselines.</p></div><div className="flowStep"><b>Untouched holdout</b><p>Freeze candidate weights and probability calibration before a later untouched window, then evaluate non-overlapping origins that are never used to tune the model.</p></div></div></section>
 <h2>Publication is a separate decision</h2><p>A model can produce internal research evidence without being allowed to publish a numeric target. V6 requires positive chronological point and probability skill, sufficient untouched-holdout evidence, no active recent-skill drift, an acceptable market-data integrity state, a valid market session where applicable, and no severe terminal jump regime. Failure of those gates produces RESEARCH_ONLY or ABSTAIN with point targets removed.</p>
 <h2>What a published forecast number means</h2><p>When publication is qualified, the center comes from the adaptive ensemble after evidence-aware shrinkage. It is an experimental conditional estimate, not a guaranteed price, recommendation or promise of future performance. Uncertainty intervals remain visible research evidence even when a point target is withheld where the evidence supports them.</p>
 <h2>Why multiple checkpoints</h2><p>A single terminal target hides path uncertainty. Up to five checkpoints expose the qualified path across the requested horizon. For non-publishable states, their numeric prices and changes are null rather than silently showing research-only targets.</p>
 <h2>Dependence-adjusted evidence</h2><p>Adjacent market observations are not independent. Zachitan spreads selected historical analogues apart in time and aggregates their weights into horizon-sized temporal blocks. The smaller of raw weighted effective sample size and block-adjusted effective sample size is used for evidence thresholds, reducing false confidence from many nearly identical neighbouring observations.</p>
 <h2>Walk-forward validation</h2><p>Validation origins are separated by at least the forecast horizon to reduce overlapping-target leakage. At each origin Zachitan forecasts from the historical prefix only, evaluates the later realized value, and measures error skill against unchanged price plus probability skill against a 50/50 baseline. Candidate weights are derived from earlier resolved origins rather than future outcomes.</p>
 <h2>Frozen untouched publication holdout</h2><p>The later holdout is reserved after the training/validation segment. Candidate weights and probability-calibration strength are frozen before that holdout begins. Holdout origins are chronological and non-overlapping. Their outcomes measure point skill, Brier skill and direction accuracy without feeding back into the weights being evaluated. V6 also reports uncertainty around holdout skill rather than treating a small positive estimate as certainty.</p>
 <h2>Recent-skill drift</h2><p>Recent holdout performance is compared with the earlier holdout window. If recent point or probability skill falls below its naïve baseline, or deteriorates materially relative to the earlier window, drift is marked active and numeric publication fails closed. Drift is evidence about model reliability in the recent regime; it is not a claim about why the market changed.</p>
 <h2>Model-history independence</h2><p>The chart window is presentation state, not model evidence. Zachitan fetches a larger model-history window based on provider, interval and forecast horizon, then slices a separate display window. Changing chart zoom therefore cannot manufacture or remove validation evidence. Provider history limits are disclosed and can leave qualification insufficient.</p>
 <h2>Data integrity and exchange closures</h2><p>Invalid OHLC rows, duplicates, ordering defects and unexpected same-session gaps are measured separately. For sessioned Yahoo intraday data, ordinary overnight or cross-date exchange closures are counted as expected closure gaps instead of being mislabeled as missing market data. Critical integrity failures override an otherwise publishable forecast.</p>
 <h2>Forecast time policy</h2><p>Crypto is continuous, so observation horizons can be translated into approximate wall-clock checkpoints. Exchange-bound instruments do not fabricate future trading dates when an authoritative future exchange calendar is unavailable: they retain observation offsets instead. Reference-rate series likewise avoid inventing an exact future publication timestamp.</p>
 <h2>Calibration and evidence scores</h2><p>Calibration is shown only when chronological validation is available. Probability confidence is shrunk toward 50/50 when measured skill is weak or negative. Evidence and calibration scores summarize measured support; neither is the probability that a forecast will be correct.</p>
 <h2>World, news and microstructure evidence</h2><p>World-state feeds, news, filings and venue microstructure are displayed separately from the price forecast unless a source family demonstrates target-specific incremental predictive value out of sample. Multiple publishers do not automatically make a claim true or predictive.</p>
 <h2>Benchmark policy</h2><p>The scheduled multi-asset benchmark evaluates both walk-forward validation and the frozen untouched holdout across several asset classes and horizons. A successful workflow run only means the benchmark executed. Broad predictive-skill claims require the report's explicit cross-asset thresholds to pass; otherwise the report states that such claims are not permitted.</p>
 <h2>What remains experimental</h2><ul><li>Positive predictive skill is not assumed and may disappear by asset, timeframe, horizon or regime.</li><li>Untouched-holdout qualification is evidence, not a guarantee of future performance.</li><li>Empirical intervals are not guarantees of future coverage.</li><li>Yahoo-backed market and option transport is best-effort and is not a licensed exchange entitlement.</li><li>Strict cross-instance rate limiting and globally durable precomputed model state require external durable infrastructure beyond the current zero-cost runtime baseline.</li></ul>
 <h2>Truth contract</h2><p>Every visible observation retains its source and timing semantics. Missing or licensed data stays missing or gated. Validation is not renamed into accuracy, an untouched holdout is not reused for tuning, active drift cannot be hidden behind a numeric target, and exact future exchange dates are not fabricated when they cannot be verified.</p>
 </div><Footer/></div>}
