import Footer from '@/app/components/Footer';

export default function Page(){return <div className="page"><div className="legal" style={{maxWidth:1100}}><p className="eyebrow">Public methodology</p><h1 style={{fontSize:58,letterSpacing:'-.065em',margin:'0 0 18px'}}>How Zachitan builds and tests an experimental forecast.</h1><p className="bodycopy" style={{fontSize:17}}>Zachitan v4.1 is a source-first empirical forecasting research system. Because this repository is public, the implementation is inspectable; the methodology page therefore describes what the engine actually does rather than implying that public equations or weights are hidden.</p>
 <section className="section"><div className="flow"><div className="flowStep"><b>Observe</b><p>Pull chronological observations with provider, timestamp, timing and rights metadata.</p></div><div className="flowStep"><b>Qualify</b><p>Reject malformed OHLC rows, preserve source timing and measure freshness.</p></div><div className="flowStep"><b>Represent</b><p>Represent market state using returns, volatility, RSI, moving-average distance, ATR, volume anomaly and rolling-range position.</p></div><div className="flowStep"><b>Compare + project</b><p>Find similar historical states, diversify them in time, then construct weighted empirical future-return distributions.</p></div><div className="flowStep"><b>Walk forward</b><p>Rebuild old forecasts using only information available at each origin and compare them with later observations and simple baselines.</p></div></div></section>
 <h2>What a forecast number means</h2><p>The forecast center is the weighted median-like outcome of comparable historical future returns after evidence-aware shrinkage toward the current price. It is an experimental conditional estimate, not a guaranteed target.</p>
 <h2>Why five checkpoints</h2><p>A single terminal target hides path uncertainty. Up to five checkpoints expose the projected center, probability of finishing above the current price and empirical uncertainty bands at different positions inside the requested horizon.</p>
 <h2>Dependence-adjusted evidence</h2><p>Adjacent market observations are not independent. Zachitan therefore spreads selected historical analogues apart in time and aggregates their weights into horizon-sized temporal blocks. The smaller of raw weighted effective sample size and block-adjusted effective sample size is used for evidence thresholds. This reduces false confidence from many nearly identical neighbouring observations.</p>
 <h2>Evidence score</h2><p>The evidence score summarizes dependence-adjusted sample size, concentration of neighbour weights and measured validation quality when validation exists. It is not the probability that a forecast will be correct.</p>
 <h2>Calibration score</h2><p>The calibration score is shown only when chronological validation is available. It combines point-error skill relative to an unchanged-price baseline, Brier probability skill relative to a 50/50 baseline, interval-coverage quality and validation sample sufficiency. If validation is unavailable, the score is shown as N/A rather than a fabricated fallback number.</p>
 <h2>Walk-forward validation</h2><p>Validation origins are separated by at least the forecast horizon to reduce overlapping-target leakage. At each origin Zachitan forecasts from the historical prefix only, then evaluates the later realized value. The terminal reports mean and median error, a MASE-like ratio versus unchanged price, error skill versus unchanged price, direction accuracy, momentum-direction baseline accuracy, Brier score and skill, log loss, selective accuracy and empirical interval coverage.</p>
 <h2>Positive skill is not assumed</h2><p>If the forecast does not beat the displayed naïve point and probability baselines on the available validation window, the product states that no positive baseline skill was demonstrated. A forecast can still be displayed as research output, but the UI does not rename model complexity into accuracy.</p>
 <h2>Forecast time policy</h2><p>Crypto is a continuous 24/7 market, so forecast observations can be translated into approximate wall-clock checkpoints. For daily/reference-rate data Zachitan uses weekday business-day estimates. For non-continuous intraday markets, Zachitan may show future observation numbers instead of manufacturing timestamps through overnight or closed exchange sessions.</p>
 <h2>World, news and microstructure evidence</h2><p>World-state feeds, news, filings and venue microstructure are displayed separately from the price forecast unless a source family demonstrates target-specific incremental predictive value out of sample. News retrieval also clusters near-duplicate headlines and reports source diversity, but multiple publishers do not automatically make a claim true or predictive.</p>
 <h2>Recurring-investment analysis</h2><p>Monthly contribution replay uses actual available observations. XIRR includes dated cash flows. Maximum drawdown is measured on the underlying NAV/price rather than raw contributed portfolio value, so additional contributions cannot artificially hide an underlying loss.</p>
 <h2>What remains experimental</h2><ul><li>The historical-analogue forecast itself may or may not exhibit positive skill for a specific asset, timeframe or regime.</li><li>Empirical intervals are not guarantees of future coverage.</li><li>Business-day time estimates do not model every exchange holiday.</li><li>Yahoo-backed market and option transport is best-effort and is not a licensed exchange entitlement.</li><li>Broad claims of forecast accuracy require the independent multi-asset protocol in VALIDATION_PROTOCOL.md.</li></ul>
 <h2>Truth contract</h2><p>Every visible observation must retain a source and timing label. Experimental outputs remain experimental. Missing or licensed data stays missing or gated. Validation metrics are never renamed into accuracy guarantees, and unavailable calibration is not represented by an arbitrary number.</p>
 </div><Footer/></div>}
