import Footer from '@/app/components/Footer';
export default function Page(){return <div className="page"><div className="legal" style={{maxWidth:1100}}><p className="eyebrow">Public methodology</p><h1 style={{fontSize:58,letterSpacing:'-.065em',margin:'0 0 18px'}}>How to understand Zachitan without exposing the engine.</h1><p className="bodycopy" style={{fontSize:17}}>Zachitan v4 is a source-first empirical forecasting research system. The public methodology explains the data contract, validation discipline and meaning of the visible outputs. It intentionally does not publish proprietary feature transformations, weighting constants, internal ranking rules, source-specific mappings or production thresholds.</p>
 <section className="section"><div className="flow"><div className="flowStep"><b>Observe</b><p>Pull real observations with provider, timestamp, timing and rights metadata.</p></div><div className="flowStep"><b>Qualify</b><p>Reject malformed, contradictory or unusable observations and measure freshness.</p></div><div className="flowStep"><b>Represent</b><p>Turn current market behavior into a comparable state without exposing the private representation.</p></div><div className="flowStep"><b>Compare + project</b><p>Use comparable historical regimes to construct empirical future distributions.</p></div><div className="flowStep"><b>Walk forward</b><p>Evaluate old predictions only against data that arrived later, then score calibration and errors.</p></div></div></section>
 <h2>What a forecast number means</h2><p>The center is the median-like central outcome of the weighted historical future distribution after evidence-aware stabilization. It is not a guaranteed target. The 50%, 80%, 90%, 95% and 99% ranges describe increasingly wider parts of the empirical outcome distribution; wider ranges are withheld when there is not enough effective evidence to estimate them responsibly.</p>
 <h2>Why there are five forecast checkpoints</h2><p>A single terminal number hides the path. Zachitan therefore shows up to five checkpoints inside the requested horizon. Each checkpoint includes its own central value, directional probability and uncertainty interval. This makes it easier to distinguish a forecast that drifts gradually from one that has wide path uncertainty.</p>
 <h2>Evidence score</h2><p>The evidence score summarizes whether there are enough useful historical analogues, whether the evidence is overly concentrated in a few examples, and whether the historical validation is reasonably coherent. It is not a probability that the forecast will be correct.</p>
 <h2>Calibration score</h2><p>Calibration examines whether historical forecast errors and interval coverage behave consistently in chronological testing. A high score does not mean that future markets will repeat the past. It means the historical prediction distributions were better behaved under the chosen validation protocol.</p>
 <h2>Walk-forward validation</h2><p>At each historical checkpoint, Zachitan forms a forecast using only data that would have existed at that point, then compares it with the later realized observation. This reduces look-ahead contamination. The terminal reports direction accuracy, median absolute percentage error, selective accuracy for stronger directional calls, and empirical interval coverage.</p>
 <h2>World evidence</h2><p>World-state connectors are deliberately displayed separately from the market forecast unless a source family has a validated target-specific causal or predictive contribution. More data is not automatically better. Unvalidated signals can increase overfitting and false confidence.</p>
 <h2>What Zachitan does not publish</h2><ul><li>Exact feature equations or transforms.</li><li>Internal feature and source weights.</li><li>Similarity-distance construction and production thresholds.</li><li>Source-to-target causal mappings.</li><li>Private robustness heuristics, guardrails and ranking logic.</li><li>Any future proprietary research added after the beta.</li></ul>
 <h2>What the platform still owes the user</h2><p>Every visible market observation must retain a source and timing label. Every forecast must remain explicitly experimental. Missing or licensed data must remain missing or gated. Validation metrics must never be renamed into “accuracy guarantees.”</p>
 </div><Footer/></div>}
