import Footer from '@/app/components/Footer';
export default function Page(){return <div className="page"><article className="legal"><p className="eyebrow">Terms of use · Zachitan v4 research beta</p><h1>Terms</h1><p>These terms govern the public Zachitan v4 research beta operated by Aphelion Private Limited. By using the beta, you acknowledge the experimental and source-dependent nature of the service.</p>
<h2>Research software, not a brokerage or adviser</h2><p>Zachitan does not execute trades, hold client assets, route orders, promise returns or guarantee future prices. Forecasts, scores, intervals, simulations, scenario outputs, watchlists and research suggestions are informational research outputs and are not personalized investment, legal, tax or accounting advice.</p>
<h2>No guarantee of accuracy, latency or availability</h2><p>Observed values come from identified third-party or public providers. Markets can be real-time, delayed, end-of-day, reference-rate based or unavailable depending on instrument, venue, entitlement and source. Third-party feeds can fail, change or contain errors. Zachitan may withhold a value rather than substitute fabricated data.</p>
<h2>Forecasts are uncertain</h2><p>Experimental predictions are based on historical evidence and validation protocols. Historical similarity does not guarantee future repetition. Probabilities and confidence ranges are estimates, not promises. Evidence or calibration scores are not probabilities of profit or correctness.</p>
<h2>Options, futures and leveraged instruments</h2><p>Derivatives can involve substantial risk. The public beta may show published option-chain or futures information when a legitimate source is available, but it does not provide exchange-entitled professional data unless explicitly stated. Do not use a delayed or best-effort feed for time-critical execution decisions.</p>
<h2>SIP and historical simulations</h2><p>SIP simulations use historical fund/NAV observations and simplified recurring contributions. Unless explicitly shown, they do not model taxes, brokerage, loads, exit fees, tracking error, cash drag, dividend treatment, slippage, currency conversion or future returns. Past simulated performance is not future performance.</p>
<h2>Source and intellectual-property rights</h2><p>Third-party data and content remain subject to their providers’ rights and terms. Zachitan’s application code, research design, internal feature engineering, model transformations, weighting logic, robustness methods, non-public formulas and proprietary research are reserved. The public Methodology page is explanatory and does not grant rights to reverse engineer private model internals.</p>
<h2>Acceptable use</h2><p>Do not attempt to bypass provider rate limits, credentials, paywalls, exchange entitlements or access controls through Zachitan. Do not use the service to misrepresent delayed/best-effort data as licensed real-time data or to create deceptive financial claims.</p>
<h2>Beta changes</h2><p>The research beta can change materially, including models, providers, screens, available instruments, terms, source contracts and retention behavior. Features can be withdrawn where data rights, reliability or safety requirements are not met.</p>
<h2>Limitation</h2><p>To the extent permitted by applicable law, the beta is provided on an experimental, as-available basis without a warranty that it will meet a particular trading, investment or commercial purpose. Users remain responsible for independent verification and their own decisions.</p>
<h2>Contact</h2><p>Questions about these terms can be sent to <a href="mailto:dharan@aphelion.life">dharan@aphelion.life</a>.</p><p><b>Effective:</b> 8 August 2026. <b>Version:</b> Zachitan v4 research beta.</p></article><Footer/></div>}
